### ISSUE TITLE
Browser Link seems broken

### ISSUE THREAD

**Issue by ilmax** [aspnet/Mvc#1263]
Just installed VS14 CTP4, created a new vNext web application project and press F5, and the F12 (in Chrome) I see this exception

```
Browser Link: Exception thrown when trying to invoke Browser Link extension callback "microsoft.visualstudio.web.browserlink.sourcemappingextensionfactory.getCssMappingData":
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Web.PageInspector.Common.BlockDiffer.SymbolTable.AddLeftBlocks(BlockList blocks)
   at Microsoft.VisualStudio.Web.PageInspector.Common.BlockDiffer.SymbolTable..ctor(BlockList left, BlockList right)
   at Microsoft.VisualStudio.Web.PageInspector.Common.BlockDiffer.BuildSymbolTable()
   at Microsoft.VisualStudio.Web.PageInspector.Common.BlockDiffer.Analyze()
   at Microsoft.VisualStudio.Web.PageInspector.Package.CssMappingDataProvider.GetRangesOfCssDomRules(Uri cssFilePath, String[] selectorTextForDomRules)
   at Microsoft.VisualStudio.Web.BrowserLink.SourceMappingExtension.getCssMappingData(String cssUrl, String[] selectors)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Web.BrowserLink.ClientMessaging.DispatchMessage(BrowserLinkConnection connection, MessageArgs obj)
```

Happens with both ASP.NET 5.0 and ASP.NET Core 5.0.

**Comment by danroth27** [comment]
@windhandel This bug is pretty old and was closed a while ago, so you should probably open a new issue for the problem you are seeing with detailed steps on how to reproduce the issue (ex what version of Visual Studio 2015 are you using?). Thanks!
