### ISSUE TITLE
Return IQueryable<T> with Web API shim causes XmlSerializationErrors

### ISSUE THREAD

**Issue by suhasj** [aspnet/Mvc#1508]
Using the Web API shim, if the controller returns IQueryable and the client accept header is 'application\xml', the converting the return type to xml causes xml serialization errors. Exception stack as below 

``` [ERROR:Microsoft.AspNet.Server.WebListener.MessagePump] ProcessRequestAsync
System.Runtime.Serialization.SerializationException: Type 'Microsoft.Data.Entity.DbSet`1[[MyApp.Controllers.Person, MyApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' with data contract name 'ArrayOfPerson:http://schemas.datacontract.org/2004/07/MyApp.Controllers' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.WriteObject(XmlWriter writer, Object graph)
   at Microsoft.AspNet.Mvc.XmlDataContractSerializerOutputFormatter.WriteResponseBodyAsync(OutputFormatterContext context)
   at Microsoft.AspNet.Mvc.OutputFormatter.<WriteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.ObjectResult.<ExecuteResultAsync>d__1.MoveNext() ```

**Comment by yishaigalatzer** [comment]
Looks related to the `WrapperFactory`

**Comment by kichalla** [comment]
Commit: e5176d22f6d2b3efacbed923fae1400903909766 fixes this issue
