### ISSUE TITLE
[Build] Functional tests intermittently fail with OOM

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1753]
Running .`\build` fails on the project with the following stack trace:
```C#
      System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
      Stack Trace:
            at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
            at System.Reflection.Internal.NativeHeapMemoryBlock..ctor(Int32 size)
            at System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(Stream stream, Boolean isFileS
tream, Int64 start, Int32 size)
            at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, Nullable`1
sizeOpt)
            at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
         D:\work\katana\mvc\src\Microsoft.AspNet.Mvc.Razor\Compilation\RoslynCompilationService.cs(191,0): at Microsoft.
AspNet.Mvc.Razor.RoslynCompilationService.<>c__DisplayClass3.<CreateMetadataFileReference>b__4(String _)
            at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         D:\work\katana\mvc\src\Microsoft.AspNet.Mvc.Razor\Compilation\RoslynCompilationService.cs(187,0): at Microsoft.
AspNet.Mvc.Razor.RoslynCompilationService.CreateMetadataFileReference(String path)
         D:\work\katana\mvc\src\Microsoft.AspNet.Mvc.Razor\Compilation\RoslynCompilationService.cs(168,0): at Microsoft.
AspNet.Mvc.Razor.RoslynCompilationService.ConvertMetadataReference(IMetadataReference metadataReference)
         D:\work\katana\mvc\src\Microsoft.AspNet.Mvc.Razor\Compilation\RoslynCompilationService.cs(142,0): at Microsoft.
AspNet.Mvc.Razor.RoslynCompilationService.GetApplicationReferences()
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
            at System.Lazy`1.get_Value()
```

Requires investigating to identity if this is a failure due to the way functional tests are set up or if it's something that could also affect runtime.

**Comment by yishaigalatzer** [comment]
@pranavkm says you have a PR coming for this

**Comment by dougbu** [comment]
@pranavkm did a94d5223e1748b24a023fffbb8852066a028f40f fix this issue?
