### ISSUE TITLE
Investigate Xml formatters tests failures on Windows 2008 R2 OS

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1878]
![image](https://cloud.githubusercontent.com/assets/6559784/5880879/c3148998-a2f0-11e4-94cc-eaa0a3a76d0f.png)

**Comment by kichalla** [comment]
@victorhurdugaci

**Comment by rynowak** [comment]
Those two FiltersTests seem unlikely to be related to Xml Formatting

**Comment by kichalla** [comment]
Actually those tests also are failing due to xml formatter issues since in the result filter the test is explicitly using xml serializer output formatter..

**Comment by victorhurdugaci** [comment]
Just for reference, the failures are:

```
Assert.Equal() Failure
                                    (pos 58)
 Expected: úúú<DummyClass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instaúúú
 Actual:   úúú<DummyClass xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlnúúú
                                    (pos 58)
    at Microsoft.AspNet.Mvc.Core.XmlSerializerOutputFormatterTests.<SuppliedWriterSettings_TakeAffect>d__7.MoveNext() in C:\BuildAgent\work\cddf23d85192f3c3\Universe\Mvc\test\Microsoft.AspNet.Mvc.Core.Test\Formatters\XmlSerializerOutputFormatterTests.cs:line 105
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
