### ISSUE TITLE
Functional tests fail due to XML serialization differences w/ CLR / x64

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2311]
follow up to #1878.  looks like we have the `XmlAssert` capability to ignore XML serialization differences but are not using this in `XmlOutputFormatterTests`.

current failures with CLR runtime and x64 architecture (other combinations seem to work fine):
```
   Microsoft.AspNet.Mvc.FunctionalTests.XmlOutputFormatterTests.XmlSerializerOutputFormatterIsCalled [FAIL]
      Assert.Equal() Failure
                                    ↓ (pos 20)
      Expected: <DummyClass xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta···
      Actual:   <DummyClass xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln···
                                    ↑ (pos 20)
      Stack Trace:
         XmlOutputFormatterTests.cs(55,0): at Microsoft.AspNet.Mvc.FunctionalTests.XmlOutputFormatterTests.<XmlSerializerOutputFormatterIsCalled>d__4.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Microsoft.AspNet.Mvc.FunctionalTests.XmlOutputFormatterTests.XmlSerializerOutputFormatter_WhenDerivedClassIsReturned [FAIL]
      Assert.Equal() Failure
                                    ↓ (pos 20)
      Expected: <DummyClass xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta···
      Actual:   <DummyClass xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln···
                                    ↑ (pos 20)
      Stack Trace:
         XmlOutputFormatterTests.cs(96,0): at Microsoft.AspNet.Mvc.FunctionalTests.XmlOutputFormatterTests.<XmlSerializerOutputFormatter_WhenDerivedClassIsReturned>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    Microsoft.AspNet.Mvc.FunctionalTests

```

**Comment by dougbu** [comment]
fixed in 689f5bf
