### ISSUE TITLE
If you add a Console logger when AddWebApiConventions is enabled, startup fails.

### ISSUE THREAD

**Issue by darrelmiller** [aspnet/Mvc#2611]
Object reference is equal null

   at Microsoft.AspNet.Mvc.Logging.ActionDescriptorValues.<>c.<.ctor>b__0_5(KeyValuePair`2 i)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.AspNet.Mvc.Logging.ActionDescriptorValues..ctor(ActionDescriptor inner)
   at Microsoft.AspNet.Mvc.Core.DefaultActionDescriptorsCollectionProvider.GetCollection()
   at Microsoft.AspNet.Mvc.Core.DefaultActionDescriptorsCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNet.Mvc.Routing.AttributeRoute.GetInnerRoute()
   at Microsoft.AspNet.Mvc.Routing.AttributeRoute..ctor(IRouter target, IActionDescriptorsCollectionProvider actionDescriptorsCollectionProvider, IInlineConstraintResolver constraintResolver, ILoggerFactory loggerFactory)
   at Microsoft.AspNet.Mvc.Routing.AttributeRouting.CreateAttributeMegaRoute(IRouter target, IServiceProvider services)
   at Microsoft.AspNet.Builder.BuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Microsoft.AspNet.Builder.BuilderExtensions.UseMvc(IApplicationBuilder app)
   at Mvc6Sandbox.StartupImplementation.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in C:\Users\Darrel\Documents\Source\GitHub\darrelmiller\Mvc6Sandbox\Mvc6SandboxApi\Startup.cs:line 42

Here is my startup:

public class Startup
    {

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging();
            services.AddMvc();
            services.AddWebApiConventions();
        }

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(LogLevel.Verbose);
            app.UseMvc();
        }
    }

**Comment by rynowak** [comment]
How old is this build? `ActionDescriptorValues` and related logging code was removed a long while ago.

**Comment by darrelmiller** [comment]
It's the beta4.  I'll see if I can repro in beta5 and reopen an issue if I can.

**Comment by rynowak** [comment]
@darrelmiller thanks. I'll likely that we just had an undiscovered bug in the logging code that could be triggered when using the webapi conventions. Regardless, all of that logging code was removed.
