### ISSUE TITLE
ASP.NET 5 Beta 7 Build Errors in Test Projects

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#2855]
I'm getting the following error when trying to build the tests. I raised [this](https://stackoverflow.com/questions/31596455/how-to-get-asp-net-5-beta-7-mvc-solution-building) StackOverflow post about it too.

```
------ Discover test started ------
Cannot discover test extensions installed by NuGet. The NuGet service is not available. Tests may not be found due to missing test adapter extensions.
------ Test started: Project: Microsoft.AspNet.Mvc.Core.Test ------
Starting  Microsoft.Framework.TestHost [C:\Users\Rehan\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\dnx.exe --appbase "C:\Git\Mvc\test\Microsoft.AspNet.Mvc.Core.Test" Microsoft.Framework.ApplicationHost --port 44096 Microsoft.Framework.TestHost --port 44324]
Connected to Microsoft.Framework.TestHost
Discovering tests in 'C:\Git\Mvc\test\Microsoft.AspNet.Mvc.Core.Test\project.json'
Error discovering tests in 'C:\Git\Mvc\test\Microsoft.AspNet.Mvc.Core.Test\project.json'\r\nSystem.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Value cannot be null.
Parameter name: type
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: Value cannot be null.
Parameter name: type<---

========== Discover test finished: 0 found (0:00:02.2580393) ==========
```

**Comment by danroth27** [comment]
@rynowak Please take a look at this one.

**Comment by rynowak** [comment]
@vijayrkn is going to take a look. We can't find out what's going on without debugging the VS code.

**Comment by rynowak** [comment]
@RehanSaeed - Can you please try using dnx version 12274 or newer? We think this is fixed, but would like to hear back from you that this is resolved.
