### ISSUE TITLE
DefaultObjectValidator runs into StackOverflow when using Dates in model.

### ISSUE THREAD

**Issue by kalluri-nb** [aspnet/Mvc#2912]
The DefaultObjectValidator fails with StackOverflow exception when using DateTime properties.      
This happens because of the Date property in DateTime object which recursively tried to create the model for DateTime.
When adding a Date property to Person class in Microsoft.AspNet.Mvc.Core.Tests 

```
Test Name:	DefaultObjectValidatorTests.ExpectedValidationErrorsRaised
Test FullName:	Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidatorTests.ExpectedValidationErrorsRaised
Test Source:	C:\dev\git\aspnet\mvc\test\Microsoft.AspNet.Mvc.Core.Test\ModelBinding\Validation\DefaultObjectValidatorTests.cs : line 210
Test Outcome:	Failed
Test Duration:	0:00:00.92

Result1 Name:	DefaultObjectValidatorTests.ExpectedValidationErrorsRaised
Result1 Outcome:	Failed
Result1 Duration:	0:00:00.103
Result1 StackTrace:	
at System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack()
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 61
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateChildNodes(String currentModelKey, ModelExplorer modelExplorer, ValidationContext validationContext) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 193
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 119
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateChildNodes(String currentModelKey, ModelExplorer modelExplorer, ValidationContext validationContext) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 193
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 119
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateChildNodes(String currentModelKey, ModelExplorer modelExplorer, ValidationContext validationContext) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 193
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 119
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateChildNodes(String currentModelKey, ModelExplorer modelExplorer, ValidationContext validationContext) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 193
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 119
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateChildNodes(String currentModelKey, ModelExplorer modelExplorer, ValidationContext validationContext) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 193
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 119
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateChildNodes(String currentModelKey, ModelExplorer modelExplorer, ValidationContext validationContext) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 193
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.ValidateNonVisitedNodeAndChildren(String modelKey, ValidationContext validationContext, IList`1 validators) in C:\dev\git\aspnet\mvc\src\Microsoft.AspNet.Mvc.Core\ModelBinding\Validation\DefaultObjectValidator.cs:line 119
   at Microsoft.AspNet.Mvc.ModelBinding.
```

**Comment by dougbu** [comment]
@kalluri-nb what is the exact type of the `Date` property you added? Does the property have any attributes on it?

**Comment by kalluri-nb** [comment]
Its a DateTime type property. The ModelExplorer keeps recursively building the model for DateTime.Date which again is a DateTime.

**Comment by rynowak** [comment]
@Eilon @danroth27 - this scenario **exactly** is that `ExcludeValidationFilters` are for.

@kalluri-nb - have you don't anything to `MvcOptions.ExcludeValidationFilters`? `DateTime` is part of a known list of a types that we don't recurse into for validation. If you've cleared this list, it would do exactly this. If you haven't messed with that option at all, then we've got a genuine bug.

**Comment by kalluri-nb** [comment]
I was working on a Custom ObjectModelValidator. I missed the part where the DefaultObjectModelValidator is initialized using a factory rather than direct DI component. 
I was expecting the IExclueValidationFilters to be injected directly into the object validator. Why can't we have the collection directly injected calling the constructor explicitly.

**Comment by rynowak** [comment]
> Why can't we have the collection directly injected calling the constructor explicitly.

The collection of validation filters is part of MVC options. If you want to DI it, you can either use a factory, or write something like: `public MyObjectValidator(IOptions<MvcOptions> ...)`

Be careful trying to replace `DefaultObjectValidator` - it's the whole validation system, not the validation for an individual item.

**Comment by kalluri-nb** [comment]
I got it working by injecting the IOptions<MvcOptions>. Thank you.
