### ISSUE TITLE
TempData fails silently without sessions middleware

### ISSUE THREAD

**Issue by newsash** [aspnet/Mvc#3068]
Following action results in empty response:
```c#
[HttpGet]
public async Task<IActionResult> Index()
{
    TempData["test"] = "test";

    return View(await messageBus.Query(new FindUsers()));
}
```

**Comment by kichalla** [comment]
What version of MVC package are you using? I am able to repro what you are seeing...if you had enabled logging(ex: console, debug or eventlog) you should be seeing a detail like below

```
System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNet.Http.Internal.DefaultHttpContext.get_Session()
   at Microsoft.AspNet.Mvc.SessionStateTempDataProvider.SaveTempData(HttpContext context, IDictionary`2 values)
   at Microsoft.AspNet.Mvc.TempDataDictionary.Save()
   at Microsoft.AspNet.Mvc.SaveTempDataFilter.OnResourceExecuted(ResourceExecutedContext context)
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeResourceFilterAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__41.MoveNext()
```

**Comment by newsash** [comment]
I'm using beta6 and I didn't see this detail. Problem can be easily reproduced in VS2015 ASP.NET Web Application template by adding TempData to Index action of HomeController.

**Comment by danroth27** [comment]
Let's see if we can provide a better error message.
