### ISSUE TITLE
Content negotiation fails in subsequent requests accepting same media type

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3140]
The @d03a851 could not remove the functional test `TestHelper` class in part because three test methods in `WebApiCompatShimBasicTest` cannot share a `TestServer` instance when using Core CLR. This issue is separate from #3139 because nothing about these tests should require a one-off server and we could have an underlying product issue here. The problem does not appear to involve inconsistent contexts, `HttpRequestMessage` or header reuse, or content negotiation state held in the server. Even so the tests fail consistently.

#### Details
Failures when sharing a `TestServer` instance and using Core CLR affect the following test methods:
- `ApiController_CreateResponse_Conneg()`, 2 of 4 test cases fail
- `ApiController_CreateResponse_HardcodedMediaType()`, 2 of 2 test cases fail
- `ApiController_CreateResponse_Conneg_Error()`, 2 of 4 test cases fail

The specific failures do not change between running every functional test and running just those in `WebApiCompatShimBasicTest`. On the other hand, failures change if the `[InlineData]` order changes or test methods are run individually. Removing the apparent failure cases from one run does not remove all failures in the next, just shifts to one of the remaining cases. Failures at least seem consistent between runs for a particular setup.

Nothing should be running in parallel when running just tests in this class. xUnit treats each test class as a collection and runs tests within collections alphabetically, not in parallel. The output sometimes looks mixed-up when I add `Console.WriteLine()` debugging statements but that probably relates to flushing and not concurrency.

The dougbu/max.fixtures.with.debugging server branch uses fixtures for these three test methods and includes some `WriteLine()` and `Assert()` checks to eliminate possibilities.

The `ApiController_CreateResponse_HardcodedMediaType()` tests fail when asserting the response status code e.g.
```
    Microsoft.AspNet.Mvc.FunctionalTests.WebApiCompatShimBasicTest.ApiController_CreateResponse_HardcodedMediaType(mediaType: "text/xml") [FAIL]
      Assert.Equal() Failure
      Expected: OK
      Actual:   InternalServerError
      Stack Trace:
        C:\dd\dnx\MVC\test\Microsoft.AspNet.Mvc.FunctionalTests\WebApiCompatShimBasicTest.cs(326,0): at Microsoft.AspNet.Mvc.FunctionalTests.WebApiCompatShimBasicTest.<ApiController_CreateResponse_HardcodedMediaType>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

The other tests fail when asserting the content type of the response body e.g.
```
    Microsoft.AspNet.Mvc.FunctionalTests.WebApiCompatShimBasicTest.ApiController_CreateResponse_Conneg(accept: "application/*", mediaType: "application/json") [FAIL]
      Assert.Equal() Failure
                            Γåô (pos 12)
      Expected: application/json
      Actual:   application/xml
                            Γåæ (pos 12)
      Stack Trace:
        C:\dd\dnx\MVC\test\Microsoft.AspNet.Mvc.FunctionalTests\WebApiCompatShimBasicTest.cs(302,0): at Microsoft.AspNet.Mvc.FunctionalTests.WebApiCompatShimBasicTest.<ApiController_CreateResponse_Conneg>d__18.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by dougbu** [comment]
This issue is a product bug. The DNX Core fork of the content negotiation classes from System.Net.Http.Formatting updates media types in-place when negotiation succeeds. Most importantly `OutputFormatter.SupportedMediaTypes` entries are changed during content negotiation. Services running under DNX Core and using the Web.API Compat Shim will perform content negotiation correctly just once per matched media type.

The previous functional test approach hid this issue because the formatters were recreated for every test.

Root cause is missing `.Clone()` calls in getters for `MediaTypeConstants` e.g. [`TextJsonMediaType`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.WebApiCompatShim/ContentNegotiator/MediaTypeConstants.cs#L82) and in the [`MediaTypeFormatterMatch` constructor](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.WebApiCompatShim/ContentNegotiator/MediaTypeFormatterMatch.cs#L34).

**Comment by dougbu** [comment]
Updated title and cleared labels.

@danroth27 @Eilon let me know if you want to reassign or move to another milestone.

**Comment by dougbu** [comment]
53060be
