### ISSUE TITLE
(6.0.0-beta8) ArgumentNullException caused by model validation

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#3338]
My view model that gets POSTed to the controller is raising an `ArgumentNullException` in beta8 (was not happening in beta7.)

The source of the exception is a read-only property on the view model that calls `Where` on another property of the view model which has not yet been set (it gets set in the controller.)

```
System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: source
  ParamName=source
  Source=System.Core
  StackTrace:
       at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
       at MyProject.Web.ViewModels.MyViewModel.get_MyProperty() in C:\path\to\source.cs:line 31
       at Microsoft.Framework.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
       at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultComplexObjectValidationStrategy.Enumerator.MoveNext()
       at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
       at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
       at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
       at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model)
       at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.Validate(IModelValidatorProvider validatorProvider, ModelStateDictionary modelState, ValidationStateDictionary validationState, String prefix, Object model)
       at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<BindModelAsync>d__5.MoveNext()
  InnerException: 
```

**Comment by Kagamine** [comment]
Can you post your code around source.cs line 31

**Comment by tuespetre** [comment]
Here's the gist of it:

```
public class MyViewModel
{
    [FromForm]
    public MyOtherViewModel MyPropertyThatGetsBoundFromFormAndValidated { get; set; }

    public IEnumerable<SomeClass> MyPropertyThatGetsSetInTheController { get; set; }

    public IEnumerable<SomeClass> MyComputedProperty 
        => MyPropertyThatGetsSetInTheController.Where(x => x.SomeCondition).OrderBy(x => x.SomeOrder);
}
```

**Comment by dougbu** [comment]
@tuespetre the stack trace refers to `get_MyProperty()` and your gist doesn't include a property named `MyProperty`. What were the original names?

**Comment by Kagamine** [comment]
I think [FromForm] cannot be used here. Does it can be used only in Controller?

**Comment by dougbu** [comment]
> I think [FromForm] cannot be used here.

`[FromForm]` is fine on any model-bound property -- including those in your controller. Might be confusing in a few cases but not disallowed.

**Comment by Kagamine** [comment]
Can I use [FromServices] in anywhere?

**Comment by dougbu** [comment]
@Kagamine yes, you can use `[FromServices]` on any model or controller property or action parameter.

**Comment by tuespetre** [comment]
@dougbu sorry for the inconsistency. I have updated the example in the comment above.

**Comment by dougbu** [comment]
@rynowak looks like `DefaultComplexObjectValidationStrategy` is attempting to validate get-only properties. If that makes sense, should `PropertyHelper.CallNullSafePropertyGetter()` be "safe" w.r.t. additional `Exception`s?

@tuespetre I suggest changing the `MyProperty` to detect `MyPropertyThatGetsSetInTheController == null` and return `null` in that case. Probably a good idea in general to set up your model types so they're complete after model binding.

**Comment by danroth27** [comment]
I think you could put `[BindNever]` on the two properties that are really not intended to be bound using model binding. Or maybe move those properties to a separate class so that you have separation between you binding model and your other logic.

**Comment by tuespetre** [comment]
FWIW, just tried `[BindNever]` and it did not help.
