### ISSUE TITLE
Running Error [Bug]

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3396]
after dnu restore
<pre>System.TypeLoadException: Could not load type 'Microsoft.Dnx.Runtime.PlatformServices' from assembly 'Microsoft.Dnx.Runtime.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)</pre>
dnx 1.0.0-rc1-15838

Please help someone I can't run application :|

**Comment by pranavkm** [comment]
We are in the middle of churning through some APIs. Please use the aspnetvnext feed - pointing to aspnetcidev might frequently leave you in a broken state.

**Comment by gvx111** [comment]
@pranavkm  I'm using this feeds
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="AspNetVNextBasic" value="https://www.myget.org/F/aspnetvnext" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="xUnit" value="https://www.myget.org/F/xunit/" />
  </packageSources>
</configuration>

**Comment by pranavkm** [comment]
NuGet.org has the stable beta8 bits. aspnetcidev and aspnetvnext have builds from dev that might be frequently broken. Unless you're contributing to the dev branch, I'd strongly recommend using the beta packages on NuGet.org.
