### ISSUE TITLE
Not running sample MVC

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3407]
<pre>System.InvalidOperationException: No service for type 'Microsoft.Extensions.Plat
formAbstractions.IApplicationEnvironment' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequ
iredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequ
iredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] arg
s)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String
 applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment
env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, Bootstr
apperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, Bootstrapper
Context bootstrapperContext)</pre>

**Comment by Eilon** [comment]
Looks like a dup of https://github.com/aspnet/Localization/issues/126
