### ISSUE TITLE
TryValidateModel throws exception when unit tested

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#3586]
When TryValidateModel is called in a controller, and then the controller is unit tested, the method throws exception. Tried with both beta8 and rc1. Project.json is the default one with referenced Microsoft.AspNet.Mvc, Microsoft.AspNet.Http and Xunit. In ASP.NET Web API 2, this was quite easy to test. Sample code:

Controller: 
```c#
public class HomeController : Controller
    {
        [HttpPost]
        public IActionResult Index(SomeModel model)
        {
            this.TryValidateModel(model);

            if (this.ModelState.IsValid)
            {
                return Ok();
            }

            return HttpBadRequest();
        }
    }
```

Model:
```c#
public class SomeModel
    {
        [Required]
        public int Int { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 5)]
        public string String { get; set; }
    }
```

Unit test:
```c#
[Fact]
        public void TryValidateModelTest()
        {
            // GetController is the same method used in the MVC source code tests
            var controller = GetController(new GenericModelBinder(), new CompositeValueProvider());

            controller.Index(new SomeModel()); // throws null reference exception, test fails

            Assert.False(controller.ModelState.IsValid);
        }
```

Stacktrace of the failed test:
```
Test Name:	ControllersTest.TryValidateModelTest
Test FullName:	TestApp.Tests.ControllersTest.TryValidateModelTest
Test Source:	c:\users\admin\documents\visual studio 2015\Projects\WebApplication2\src\ClassLibrary1\Class1.cs : line 48
Test Outcome:	Failed
Test Duration:	0:00:00.075

Result StackTrace:	
at Microsoft.AspNet.Mvc.ModelBinding.Validation.DataAnnotationsModelValidatorProvider.GetValidators(ModelValidatorProviderContext context)
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.GetValidators(ModelMetadata metadata)
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitSimpleType()
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.Validate(IModelValidatorProvider validatorProvider, ModelStateDictionary modelState, ValidationStateDictionary validationState, String prefix, Object model)
   at Microsoft.AspNet.Mvc.Controller.TryValidateModel(Object model, String prefix)
   at Microsoft.AspNet.Mvc.Controller.TryValidateModel(Object model)
   at TestApp.Tests.HomeController.Index(SomeModel model) in c:\users\admin\documents\visual studio 2015\Projects\WebApplication2\src\ClassLibrary1\Class1.cs:line 23
   at TestApp.Tests.ControllersTest.TryValidateModelTest() in c:\users\admin\documents\visual studio 2015\Projects\WebApplication2\src\ClassLibrary1\Class1.cs:line 51
Result Message:	Object reference not set to an instance of an object.
```
Full example available [HERE](http://stackoverflow.com/questions/33754314/tryvalidatemodel-in-asp-net-mvc-6), [HERE](https://gist.github.com/ivaylokenov/1ef672dfbb62cb691607) or [HERE](http://forums.asp.net/t/2077940.aspx?TryValidateModel+in+unit+tests). Any pointers or suggestions?

**Comment by Eilon** [comment]
In particular, is there anything we need to do to make this more unit-test friendly?

**Comment by dougbu** [comment]
We unnecessarily (attempt to) use `MvcDataAnnotationsLocalizationOptions` when there's no `IStringLocalizerFactory`. Product code fix is simple and I'll send it out shortly.

Removing `Investigate` label and putting this into RC2. @Eilon @danroth27 any objections?

**Comment by Eilon** [comment]
Yeah sounds good.

**Comment by dougbu** [comment]
6297822

**Comment by mbowman8** [comment]
I'm receiving this error when the controller is calling TryValidateModel during a unit test. What is the fix to this issue?

**Comment by Eilon** [comment]
@mbowman8 can you post a new issue with the specific code you have that's failing?

**Comment by mbowman8** [comment]
@Eilon issue #6000 has been created.

**Comment by jlpallas** [comment]
You can pass your tests moking ObjectValidator.
```
            var objectValidator = new Mock<IObjectModelValidator>();
            objectValidator.Setup(o => o.Validate(It.IsAny<ActionContext>(), 
                                              It.IsAny<ValidationStateDictionary>(), 
                                              It.IsAny<string>(), 
                                              It.IsAny<Object>()));
            controller.ObjectValidator = objectValidator.Object;
```

**Comment by m4ss1m0g** [comment]
The mocking of **ObjectValidator** doesn't work for me.
I found a really useful extension method on [Stackoverflow](https://stackoverflow.com/questions/1269713/unit-tests-on-mvc-validation/3353125#3353125)

Here the code

```
public static void ValidateViewModel<TViewModel, TController>(this TController controller, TViewModel viewModelToValidate)
            where TController : Controller
{
	var validationContext = new ValidationContext(viewModelToValidate, null, null);
	var validationResults = new List<ValidationResult>();
	Validator.TryValidateObject(viewModelToValidate, validationContext, validationResults, true);
	foreach (var validationResult in validationResults)
	{
		controller.ModelState.AddModelError(validationResult.MemberNames.FirstOrDefault() ?? string.Empty, validationResult.ErrorMessage);
	}
}
```
add **using** to the extension methods and use like this:

```
var model = new MyModel();
controller.ValidateViewModel(model);

```

**Comment by dougbu** [comment]
@m4ss1m0g this issue was closed long ago. If you cannot get something working, please open a new issue describing exactly what you're doing and what is broken.

Separately, your extension method does not use MVC except when it calls `controller.ModelState.AddModelError(...)`. In particular, `Validator.TryValidateObject(...)` does _not_ call into the MVC validation system.
