### ISSUE TITLE
NullReferenceException during model binding with optional query parameters in actions

### ISSUE THREAD

**Issue by davenewza** [aspnet/Mvc#3738]
There is an issue with the model binding of optional query parameters in actions. 

### Repro steps

Take the following controller action for example:

    [HttpGet]
    [Route("api/test")]
    public IActionResult Get(string value = "default value")
    {
        return Ok(value);
    }

Requesting with `api/test?value=something` works as it should, returning with _something_ in the response body.

Requesting with `api/test` will result in a `NullReferenceException` (detailed further below) as the framework tries to bind to the action.

### project.json extract:

    {
        ...
        "dependencies": {
          "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
          "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
          "Microsoft.AspNet.Mvc.Abstractions": "6.0.0-rc1-final",
          "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
          "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
          "Microsoft.AspNet.Authorization": "1.0.0-rc1-final",
          "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
          "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc1-final",
          "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
          "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
          "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc1-final",
          "Newtonsoft.Json": "6.0.6"
        },
        "commands": {
          "web": "Microsoft.AspNet.Server.Kestrel"
        },
        "frameworks": {
          "dnx451": { }
        },
    }

### Exception

 > System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.Mvc.ModelBinding.CompositeModelBinder.<RunModelBinders>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<BindModelAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<PopulateArgumentsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<BindActionArgumentsCoreAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllActionFiltersAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeExceptionFilterAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNet.RequestTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()

**Comment by rynowak** [comment]
@davenewza - I'm unable to reproduce this issue on rc1 or on latest bits. Is there a repo somewhere I can check out?

**Comment by davenewza** [comment]
So, the problem is that my custom model binders were returning `null` instead of `Task.FromResult(ModelBindingResult.NoResult);`

The IModelBinder.BindModelAsync comment states the following:

 > "A null return value means that this model binder was not able to handle the request. Returning null ensures that subsequent model binders are run. If a non null value indicates that the model binder was able to handle the request."

I find this misleading and difficult to troubleshoot. Potentially worth keeping this issue open.

See my [StackOverflow post here](http://stackoverflow.com/questions/34197127/exception-with-custom-model-binding-in-asp-net-5-mvc-6-rc1-api).

**Comment by rynowak** [comment]
You're right, those docs are out of date :cry:

**Comment by rynowak** [comment]
https://github.com/aspnet/Mvc/pull/3781

**Comment by Eilon** [comment]
@rynowak any work left here, now that the docs are updated?

**Comment by rynowak** [comment]
Not that I can think of

**Comment by davenewza** [comment]
Sorry, I reopened it mistakenly.
