### ISSUE TITLE
MissingFieldException when adding NodaTime JSON.net converters to MVC 6

### ISSUE THREAD

**Issue by CMircea** [aspnet/Mvc#3816]
Trying to add the converters exposed by the NodaConverters class results in the following exception on application startup:

```
System.MissingFieldException: Field not found: 'NodaTime.Serialization.JsonNet.NodaConverters.InstantConverter'.
   at WebApplication2.Startup.<>c.<ConfigureServices>b__5_0(MvcJsonOptions options)
   at Microsoft.Extensions.OptionsModel.ConfigureOptions`1.Configure(TOptions options)
   at Microsoft.Extensions.OptionsModel.OptionsManager`1.<>c.<get_Value>b__4_0(TOptions options, IConfigureOptions`1 setup)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.Extensions.OptionsModel.OptionsManager`1.get_Value()
   at Microsoft.AspNet.Mvc.Formatters.Json.Internal.MvcJsonMvcOptionsSetup.<>c__DisplayClass0_0.<.ctor>b__0(MvcOptions _)
   at Microsoft.Extensions.OptionsModel.ConfigureOptions`1.Configure(TOptions options)
   at Microsoft.Extensions.OptionsModel.OptionsManager`1.<>c.<get_Value>b__4_0(TOptions options, IConfigureOptions`1 setup)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.Extensions.OptionsModel.OptionsManager`1.get_Value()
   at Microsoft.AspNet.Mvc.ApplicationModels.DefaultApplicationModelProvider..ctor(IOptions`1 mvcOptionsAccessor)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetServices[T](IServiceProvider provider)
   at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.GetCollection()
   at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNet.Mvc.Routing.AttributeRoute.GetInnerRoute()
   at Microsoft.AspNet.Mvc.Routing.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

Steps to reproduce:
1. Create a new ASP.NET 5 project, Web API flavor.
2. In project.json remove `dnxcore50`, add dependency on `"NodaTime": "1.3.1"`, `"NodaTime.Serialization.JsonNet": "1.3.1"`, `"Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final"`
3. In Startup.cs add `app.UseDeveloperExceptionPage()` so we get a nice error page.
4. Then add the following code in `ConfigureServices`:

```
services.AddMvc().AddJsonOptions(options =>
{
    options.SerializerSettings.Converters = new List<JsonConverter>
    {
        NodaConverters.InstantConverter,
        NodaConverters.IntervalConverter,

        NodaConverters.LocalDateConverter,
        NodaConverters.LocalDateTimeConverter,
        NodaConverters.LocalTimeConverter,

        NodaConverters.OffsetConverter,
        NodaConverters.OffsetDateTimeConverter,

        NodaConverters.DurationConverter,
        NodaConverters.RoundtripPeriodConverter,
    };
});
```

You should get a nice error page like this:
![](http://i.imgur.com/dxnzXNF.jpg)

**Comment by Eilon** [comment]
I just tried these exact steps with the same versions of everything and when I run the app I got `["value1","value2"]` in my browser, which I expected.

Ultimately this error generally indicates that the version something is being *run* with is different than the version something was *compiled* with.

Might you have some other version of the NodaTime assemblies in the GAC?

**Comment by CMircea** [comment]
The thing is, I don't have NodaTime in the GAC at all and the same code does work in Web API 2 (adding the NodaTime converters to the default JSON serializer).

I figured something is wrong with what's loaded vs what's compiled, but not sure why exactly, as these are NuGet packages. In fact in the debugger I can check with reflection that the class exists and has all static members, but in code the same reflection lookup returns nothing!

**Comment by davidfowl** [comment]
Check the modules window in visual studio to see where stuff is getting loaded from.

**Comment by CMircea** [comment]
This is the only matching entry in the modules window:

    NodaTime.Serialization.JsonNet.dll	C:\Users\Mircea\.dnx\packages\NodaTime.Serialization.JsonNet\1.3.1\lib\net35-Client\NodaTime.Serialization.JsonNet.dll	No	N/A	Cannot find or open the PDB file.		77	1.03.1.0	06.03.2015 15:44	04DA0000-04DAA000	[12460] dnx.exe	[1] DefaultDomain	

I've deleted the package cache from both the DNX and NuGet folders, before doing a fresh restore. That seems like the correct path to load the package from :-/

**Comment by davidfowl** [comment]
If you remove `NodaConverters.InstantConverter` does it work?

**Comment by CMircea** [comment]
No, it complains about the next converter.

**Comment by davidfowl** [comment]
Time to make a console app.

**Comment by CMircea** [comment]
I just did that. The dependcies are Newtonsoft.Json 7.0.1, NodaTime 1.3.1, NodaTime.Serialization.JsonNet 1.3.1, targeting just dnx451.

This is Program.cs in its entirety:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using NodaTime;
using NodaTime.Serialization.JsonNet;

namespace ConsoleApp1
{
    public class Program
    {
        public class Data
        {
            public Instant Test
            {
                get;
                set;
            }
        }

        public static void Main(string[] args)
        {
            var settings = new JsonSerializerSettings
            {
                Converters = new List<JsonConverter>
                {
                    NodaConverters.InstantConverter,
                    NodaConverters.IntervalConverter,

                    NodaConverters.LocalDateConverter,
                    NodaConverters.LocalDateTimeConverter,
                    NodaConverters.LocalTimeConverter,

                    NodaConverters.OffsetConverter,
                    NodaConverters.OffsetDateTimeConverter,

                    NodaConverters.DurationConverter,
                    NodaConverters.RoundtripPeriodConverter,
                }
            };

            var data = new Data
            {
                Test = SystemClock.Instance.Now
            };

            string json = JsonConvert.SerializeObject(data, settings);

            Console.WriteLine(json);
        }
    }
}
```

This is the exception I get when I try running that program:

```
System.MissingFieldException: Field not found: 'NodaTime.Serialization.JsonNet.NodaConverters.InstantConverter'.
   at ConsoleApp1.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

:(

**Comment by davidfowl** [comment]
That exact same sample works for me.

**Comment by davidfowl** [comment]
![image](https://cloud.githubusercontent.com/assets/95136/12065864/9778a250-af93-11e5-80ca-38ad03908358.png)

**Comment by davidfowl** [comment]
Can you show more of your modules window

**Comment by CMircea** [comment]
This makes no sense whatsoever. As I said, with reflection, it doesn't work still, but in the debugger it does!

**Comment by CMircea** [comment]
Weird thing is, I can't debug the app as-is, no breakpoint is hit. I have to comment the lines creating the converters list. Here is a screenshot of the modules window for the console app.

NodaTime.Serialization.JsonNet isn't loaded, probably because I had to comment the code that references it to even start debugging.

[Modules](http://i.imgur.com/fXtMjpk.png)

**Comment by CMircea** [comment]
It is loaded if I reference NodaConverters in a typeof expression:

![Modules](http://i.imgur.com/I163peD.png)

**Comment by davidfowl** [comment]
Feels like something is lying to you but i'm not sure what.

**Comment by CMircea** [comment]
Yeah, I've seen some weird stuff, especially when working with async code, but this is quite different. I appreciate your effort on helping me debug this.

**Comment by davidfowl** [comment]
Can you come into https://jabbr.net/#/rooms/AspNetvNext or https://gitter.im/aspnet/Home

**Comment by CMircea** [comment]
I'm on the Gitter room.

**Comment by davidfowl** [comment]
Turns out the GAC is evil and a binding redirect is needed for this situation.

**Comment by CMircea** [comment]
DLL hell, 2015 version.
