### ISSUE TITLE
Add dependency on System.Runtime.Serialization.Primitives to make up for JSON.NET not including it

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3946]
When running MVC without explicitly adding System.Runtime.Serialization.Primitives when running on the .NET CLI you'll get this error:

```
An unhandled exception has occurred while executing the request
      System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

      File name: 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
         at Microsoft.AspNet.Mvc.Formatters.Json.Internal.MvcJsonMvcOptionsSetup.<>c__DisplayClass0_0.<.ctor>b__0(MvcOptions options)
         at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
         at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
         at Microsoft.AspNet.Mvc.ApplicationModels.DefaultApplicationModelProvider..ctor(IOptions`1 mvcOptionsAccessor)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetCollection()
         at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
         at Microsoft.AspNet.Mvc.Routing.AttributeRoute.GetTreeRouter()
         at Microsoft.AspNet.Mvc.Routing.AttributeRoute.RouteAsync(RouteContext context)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

It's because of https://github.com/JamesNK/Newtonsoft.Json/issues/618. DNX used to include this assembly so it wasn't needed but now it is. Until we sorta out netstandard and the process for building new style libraries we should add it as a dependency to MVC.Core.

/cc @pranavkm @rynowak

**Comment by pranavkm** [comment]
I'll address this as part of https://github.com/aspnet/Mvc/issues/3908 (although I haven't run this as yet).

**Comment by davidfowl** [comment]
@pranavkm Try running HelloMvc (https://github.com/davidfowl/dotnetcli-aspnet5/tree/master/HelloMvc) after removing that package from `project.json`

**Comment by davidfowl** [comment]
So it looks like we're going to need XDocument as well:

```
FileNotFoundException: Could not load file or assembly 'System.Xml.XDocument, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

It's all JSON.NET. Hopefully it'll all go away once we're netstandard and JSON.NET is updated to have dependencies listed.

/cc @JamesNK

**Comment by JamesNK** [comment]
When you release RC2 and the tools are there, I'll release a version with netstandard :grin:

**Comment by davidfowl** [comment]
Sure I'm just looking at what's blowing up right now
