### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by glararan** [aspnet/Mvc#4067]
Hi,

This is my first issue, if I miss something let me know.

So what's the problem?
Problem is I did something with WebAPI and then I started receiving Internal Server Error even on HomeController/Index I broke something I don't know what.

OS: Win 10 b14257 x64
DNX: 1.0.0-rc2-16357 clr x86
VS: 15 Enterprise Update 1

Deploy configuration: web

Error Home/Index:
```
> System.ArgumentNullException: Value cannot be null.
> Parameter name: source
>    at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
>    at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorBuilder.CreateMixedRoutedActionDescriptorsErrorMessage(ControllerActionDescriptor actionDescriptor, IDictionary`2 actionsForMethod)
>    at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorBuilder.ValidateActionGroupConfiguration(IDictionary`2 methodMap, ControllerActionDescriptor actionDescriptor, IDictionary`2 routingConfigurationErrors)
>    at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorBuilder.Build(ApplicationModel application)
>    at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.GetDescriptors()
>    at Microsoft.AspNet.Mvc.Controllers.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
>    at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.GetCollection()
>    at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionDescriptorsCollectionProvider.get_ActionDescriptors()
>    at Microsoft.AspNet.Mvc.Routing.AttributeRoute.GetTreeRouter()
>    at Microsoft.AspNet.Mvc.Routing.AttributeRoute.RouteAsync(RouteContext context)
>    at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

Startup class:
    
    public class Startup
    {
        MyDbContext db;

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework().AddSqlite().AddDbContext<MyDbContext>(); // db
            services.AddMvc();
            services.AddSingleton<IWebAPIRepository, WebAPIRepository>();

            // this not causing error, worked before
            db = new MyDbContext();
            db.Database.EnsureCreated();

            MyConfig.Database = db;
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseIISPlatformHandler();
            app.UseDeveloperExceptionPage();

            // this not causing error, worked before
            app.UseCookieAuthentication(options =>
            {
                options.LoginPath = "/account/login";
                options.AccessDeniedPath = "/account/forbidden";

                options.AuthenticationScheme = "Cookies";
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
            });
                        
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            app.UseStaticFiles();
            app.UseWebSockets();

            // this not causing error, worked before
            app.Map("/ws", builder =>
            {
                builder.Use(async (Context, Next) =>
                {
                    HttpContext httpContext = (HttpContext)Context;

                    if (httpContext.WebSockets.IsWebSocketRequest)
                    {
                        WebSocket socket = await httpContext.WebSockets.AcceptWebSocketAsync();

                        await Task.Delay(100);

                        if (socket != null && socket.State == WebSocketState.Open)
                        {
                            Communication comm = new Communication(socket);

                            if (DaisyConfig.WebSocket == null || DaisyConfig.WebSocket.Socket.State != WebSocketState.Open)
                                DaisyConfig.WebSocket = comm;
                        }
                    }

                    await Next();
                });
            });
        }

        public static void Main(string[] args)
        {
            var application = new WebApplicationBuilder()
                .UseConfiguration(WebApplicationConfiguration.GetDefault(args))
                .UseStartup<Startup>()
                .Build();

            application.Run();
        }
    }

[Authorize]
    public class HomeController : Controller
    {
        void PageDescription(string Title, string PageTitle, string Description)
        {
            /*ViewData["Title"]           = Title;
            ViewData["PageTitle"]       = PageTitle;
            ViewData["PageDescription"] = Description;*/
        }

        public IActionResult Index(IndexViewModel model)
        {
            //PageDescription("Dashboard", "Dashboard", "Statistics Overwiev");
            
            return View(model);
        }

        public IActionResult Blank()
        {
            return View();
        }

        public IActionResult Forms()
        {
            return View();
        }

        public IActionResult Charts()
        {
            return View();
        }

        public IActionResult Tables()
        {
            return View();
        }

        public IActionResult Bootstrap_elements()
        {
            return View();
        }

        public IActionResult Bootstrap_grid()
        {
            return View();
        }

        public IActionResult EventViewer(EventLogViewModel model)
        {
            return View(model);
        }
    }
```

Thanks for any ideas to resolve this.

Sorry for formatting, code not working :(

**Comment by glararan** [comment]
Solved, WebAPIController missed attribute [Route("api/[controller]")]

**Comment by rynowak** [comment]
Reopening this because this should not cause a crash

**Comment by ryanbrandenburg** [comment]
@glararan I couldn't get your example snippets to repro. Could you create a complete repro project and link it here as either a github repo or a zip file?

**Comment by ryanbrandenburg** [comment]
@glararan, just a reminder that we need a complete repro project in order to investigate this any further.

**Comment by glararan** [comment]
Sorry I forgot to post it here, I was so busy :/

Problem was with this class (there was missing [Route("api/")] ):

> [Route("api")]
> public class WebAPIController : Controller
>     {
>         IWebAPIRepository WebAPI { get; set; }
> 
>         public WebAPIController([FromServices] IWebAPIRepository API)
>         {
>             WebAPI = API;
>         }
> 
>         [HttpPost("Authenticate", Name = "Authenticate")] // /api/Authenticate
>         public async Task<IActionResult> Authenticate([FromBody] LoginViewModel bodyModel, LoginViewModel model)
>         {
>             if (model == null && bodyModel == null)
>             {
>                 return Ok(new { success = false });
>             }
> 
>             AuthenticationStatus result = await WebAPI.Authenticate(HttpContext.Authentication, model?.Email ?? bodyModel.Email, model?.Password ?? bodyModel.Password, model?.RememberMe ?? bodyModel.RememberMe);
> 
>             switch (result)
>             {
>                 case AuthenticationStatus.Success:
>                     return Ok(new { success = true });
> 
>                 case AuthenticationStatus.LockedOut:
>                     return Ok(new { success = false, error = "Locked out" });
> 
>                 case AuthenticationStatus.Failure:
>                 default:
>                     return Ok(new { success = false, error = "Invalid login attempt" });
>             }
>         }
> 
>         ObjectResult Ok(dynamic response)
>         {
>             return new ObjectResult(response);
>         }
> 
>         ObjectResult Ok(dynamic response, HttpStatusCode statusCode)
>         {
>             ObjectResult result = new ObjectResult(response);
>             result.StatusCode = (int)statusCode;
> 
>             return result;
>         }
>     }

If you remove that you should get error I described in first post

**Comment by ryanbrandenburg** [comment]
I tried that already (and again just now) with the latest MVC and it did not reproduce. I had to make fairly large modifications because it did not compile against current bits when dropped into an existing project though. What I'm requesting is a COMPLETE project (not snippets but a complete git repo or zip file which would compile). I'm asking this because I believe either 1) there is a part of the the project which you did not include, or which I had to remove to make compile which is causing the behavior or 2) the issue has already been fixed in MVC without being noticed. 1 is much easier to to prove, but only if I have the complete project.

**Comment by glararan** [comment]
Well, I tried to remove that Route attribute and website is still working, I guess bug is fixed without being noticed. I tried that before uploading project for you, but you wouldn't find any problem at all.

I think you can now close this issue as solved.

Thanks.
