### ISSUE TITLE
views cannot be served

### ISSUE THREAD

**Issue by ciel** [aspnet/Mvc#4189]
Using the current repository, run the `MvcSandbox` project verbatim with no changes using the following commands;

`dotnet restore`
`dotnet build`
`dotnet run`

You are served an error that views cannot be found, but it clearly lists the correct directories.

```
An unhandled exception occurred while processing the request.

InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
```

using dotnet version `1.0.0-beta-001540` and compiled against `coreclr-1.0.0-rc2-16551x64` on Windows 10x64.

**Comment by ciel** [comment]
Here's the full stack trace;

```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by pranavkm** [comment]
You'd need to specify the applicationbase. Here's what my powershell command looks lke: `dotnet run -- --applicationbase $PWD`

**Comment by ciel** [comment]
I'm not sure I understand. I can't find this documented anywhere.

**Comment by ciel** [comment]
Okay, I think I understand now. Is there any way to put this setting in a
file?

**Comment by pranavkm** [comment]
@ciel, there's a `UseApplicationBasePath` argument on `IWebHostBuilder` that you could use. Alternatively if your app is using a config file, you could add the `applicationBase` key to it.

**Comment by davidfowl** [comment]
@ciel https://github.com/aspnet/cli-samples

**Comment by ciel** [comment]
Was this changed yet again?

**Comment by davidfowl** [comment]
@ciel the name of the property changed.

**Comment by Jose-CF** [comment]
So, how to set it now? August 2017 more than one year later this issue still there.

**Comment by davidfowl** [comment]
@Jose-CF how are you seeing the issue? What does your project look like and what command did you run

**Comment by Jose-CF** [comment]
To reproduce:
* Create an ASP .NET project (tried several target frameworks, net461, net462, netcoreapp1.0, netcoreapp1.1, netcoreapp2.0 with same result).
* Install Microsoft.AspNetCore.Mvc package (as well as it dependencies).
* Create simple controller with hello world view.
* Configure the server you want, several server tried to I do believe not server related... some of the ones I tried: Kerstell, IIS.
* Run your app: tried different ways, through IIS, through a console launcher, using different dotnet sdk's... seems no difference.
* Request your hello world controller/view: Can see with the debugger and log messages the controller is found. However when creating the view... it crashes:
```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

I tried to add different locations. I also tried to hardcode the locations. Still no matter what I tried, never finds the views.
Tried with several versions of Microsoft.AspNetCore.* seems no difference. Setting the root/application base paths seems to not to fix the issue.
Also tried in different servers with Windows and Linux, still no difference, the views cannot be found.

**Comment by pranavkm** [comment]
If you're using Asp.Net Core< v2.0, you need to ensure you have `builder.UseContentRoot(Directory.GetCurrentDirectory())` in your Program.Main. I'd recommend using the Mvc template (`dotnet new mvc`) and let it wire up things for you rather installing the packages piecemeal.

**Comment by Jose-CF** [comment]
@pranavkm  Sure.
I used the template, and also tried to do from an empty project, etc.
Sure as I said in my original message, I double check all the content root and base paths are properly set.
In addition I also tried to put hardcoded paths to the views just to check out if there is a problem with that.

But from all the permutations of workarounds and things I tried nothing works. I always get that exception. So really... to me does not look like a configuration problem but like a bug.

**Comment by danroth27** [comment]
@Jose-CF Could you please zip up your project that reproduces the issue and send it to us?

**Comment by Jose-CF** [comment]
Sure... Where can I send it?! That said... really no magic in the project ... really empty. Please tell me an address where to send it.

By the way... same behavior with .NET Core 2.0

**Comment by davidfowl** [comment]
Github would be best

**Comment by Jose-CF** [comment]
I typed ```dotnet new mvc```. I think it's easier if you type it. But still, I can put it in a repo if necessary.

**Comment by davidfowl** [comment]
`dotnet new razor` works on my machine. Can you provide a bit more information?

**Comment by Jose-CF** [comment]
@davidfowl  I do believe it works in your machine. That does not really help me or anyone having this problem though ;)

So, as I stated already, when finding the view I get this exception:
```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

I tried it in Win 10 (x64), Windows Server 2016, Ubuntu, with same result unfortunately.
I tried different target frameworks, including net461, netcoreapp1.1, netcoreapp2.0 (recently) with same result unfortunately.
I also tried to hardcode the locations of the views, no luck either.

Strange, but I am not the only one experiencing it... if you google this issue you will find plenty of people stuck in this bug.

**Comment by oldsand** [comment]
I have the same  issue as well when I after I use the MapRoute inside the Startup.cs

``` Csharp
  routes.MapRoute(
                    name: "pagination",
                    template: "Products/Page{page}",
                    defaults: new { controller = "Product", action = "List" });

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Product}/{action=List}/{id?}");
)
```

**Comment by pranavkm** [comment]
@oldsand you're running in to a bug we introduced in 2.0. https://github.com/aspnet/Mvc/issues/6660#issuecomment-322613442 describes some workarounds.

**Comment by shlomishemesh1** [comment]
Hi, I have the same problem and I will be happy if someone can help me.

**Comment by pranavkm** [comment]
@shlomishemesh1 you're commenting on a closed \ resolved issue. Could you create a new work item?

**Comment by redbar0n** [comment]
FWIW, In our case we received this error when accessing `localhost:<port>/graphql` even though the `View/GraphQL/Index.cshtml` was in the right place. We got the error because `wwwroot/bundle.js` and `wwwroot/style.js` was not initally committed, since our .gitignore included `wwwroot`. Discovered it by inspecting the network traffic and seeing it was these files giving the 404 and not the `Index.cshtml` itself.
