### ISSUE TITLE
AddViewLocalization without parameters not working after latest changes in aspnet/Localization

### ISSUE THREAD

**Issue by mmalolepszy** [aspnet/Mvc#4204]
Calling AddViewLocalization extension method without parameters in Startup class, causes an exception:
```
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: setupAction
   at Microsoft.Extensions.DependencyInjection.LocalizationServiceCollectionExtensions.AddLocalization(IServiceCollection services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcLocalizationMvcBuilderExtensions.AddViewLocalization(IMvcBuilder builder, LanguageViewLocationExpanderFormat format, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcLocalizationMvcBuilderExtensions.AddViewLocalization(IMvcBuilder builder, LanguageViewLocationExpanderFormat format)
   at MyApp.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\EDU\MyApp\src\MyApp\Startup.cs:line 67
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
Snippet from my Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
    // (...)

    // Add MVC services to the services container
    services.AddMvc()
        .AddViewLocalization()
        .AddDataAnnotationsLocalization();

    // (...)
}
```
Changing above code to 
```
public void ConfigureServices(IServiceCollection services)
{
    // (...)

    // Add MVC services to the services container
    services.AddMvc()
        .AddViewLocalization(o => o.ResourcesPath = "/path/to/my/resources")
        .AddDataAnnotationsLocalization();

    // (...)
}
```
makes everything work as expected.

This problem is caused by setting `setupAction` to `null` [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Localization/DependencyInjection/MvcLocalizationMvcBuilderExtensions.cs#L46) and it started to appear after this [change](https://github.com/aspnet/Localization/pull/217) in aspnet/Localization repository.

**Comment by javiercn** [comment]
@rynowak Taking care of this.

**Comment by dougbu** [comment]
@javiercn this looks very similar to the reason MVC uses [the following](https://github.com/aspnet/Mvc/blob/354400f12bf1bb82d364eddb5710bc370384bff4/src/Microsoft.AspNetCore.Mvc.ViewFeatures/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L104) to register `IHtmlHelper<T>` in DI:
```c#
services.TryAddTransient(typeof(IHtmlHelper<>), typeof(HtmlHelper<>));
```

The service container isn't set up correctly if we instead use
```c#
services.TryAddTransient<IHtmlHelper<>, HtmlHelper<>>();
```
