### ISSUE TITLE
Adding MVC to Nightly Build Causing Missing Method Exception

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Mvc#4325]
The 20221 RC2 build was working for an example I'm working on but once I add MVC to the mix, it's failing with a Missing Method exception. I've included MVC like this (snippet of the project.json):

```
  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-rc2-*",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc2-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc2-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc2-*"
  },
```

I'm adding it to the service container (and this is where the failure happens on startup) (snippet of the startup.cs):

```
  public class Startup
  {
    // This method gets called by the runtime. Use this method to add services to the container.
    // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
    public void ConfigureServices(IServiceCollection services)
    {
      services.AddMvc();
    }
```

The exception looks like this:

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.ILibraryManager Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_LibraryManager()'.
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCoreServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at TheWorld.Startup.ConfigureServices(IServiceCollection services) in P:\examples\RC2Test\TheWorld\src\TheWorld\Startup.cs:line 19
```

**Comment by Eilon** [comment]
You should be using the AspNetCore packages - I see AspNet there.

**Comment by Eilon** [comment]
Also, the new version number for MVC is 1.0.0 (just like everything else in ASP.NET Core).

**Comment by shawnwildermuth** [comment]
Great, thanks...feel free to close
