### ISSUE TITLE
Reliability: AcessViolationException - Linux-HelloWorldMVC crash after few hours of test run.

### ISSUE THREAD

**Issue by sivagms** [aspnet/Mvc#4327]
HelloWorldMVC App |||
-------------------|------------------------|--------------------------------------
 Azure A2 VM | 80% CPU Usage | 300 concurrent connections 

4 hours of into the reliability test run  The app crashes. 

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.InvokeActionAsync(HttpContext httpContext, ActionDescriptor actionDescriptor)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.AspNetCore.Server.Kestrel.Infrastructure.LoggingThreadPool.<.ctor>b__4_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by pranavkm** [comment]
Are you using dotnet to run the app? There were issues with certain versions of it it in the past - https://github.com/dotnet/cli/issues/1785

**Comment by danroth27** [comment]
@pranavkm Please close this issue and contact @sivagms once we have taken the new .NET CLI so that they can validate that this is no longer an issue in the next stress run.

**Comment by sivagms** [comment]
This didn't show up in test runs last week..

**Comment by pranavkm** [comment]
We've updated to `1.0.0-beta-002202`. Feel free to reopen this if you're still seeing the error.
