### ISSUE TITLE
Application startup exception: System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by wesamco** [aspnet/Mvc#4400]
repro https://github.com/wesamco/prepro
# Exception 
```
C:\Users\User\Desktop\prepro\src\project (master)
λ dotnet run
Compiling project for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.3738701
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<Microsoft.Extensions.DependencyModel.RuntimeAssetGroup> Microsoft.Extensions.DependencyModel.RuntimeLibrary.get_RuntimeAssemblyGroups()'.
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.<>c.<GetCandidateAssemblies>b__5_0(RuntimeLibrary library)
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at OIDD.Startup.ConfigureServices(IServiceCollection services) in C:\Users\User\Desktop\prepro\src\project\Startup.cs:line 120
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: C:\Users\User\Desktop\prepro\src\project\bin\Debug\netcoreapp1.0\win81-x64
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

```
# Environment data
```
λ dotnet --info
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

```

**Comment by pranavkm** [comment]
You're referencing an older version of `Microsoft.Extensions.DependencyModel`. Mvc is compiled against v1.0.0-beta-002202 which is what your app should be using (as opposed to `1.0.0-beta-002171` it is currently referencing).

**Comment by Eilon** [comment]
@wesamco can you confirm if that fixes the problem?

**Comment by wesamco** [comment]
@pakrym  @Eilon I specified in project.json to use the newer
it fixed it
