### ISSUE TITLE
Uncatchable binding error using json body-posted content

### ISSUE THREAD

**Issue by Yablargo** [aspnet/Mvc#4542]
Hello.

I have a controller method that takes a Json object that has a list, and contains enum values.
```

   public IActionResult AddPatchesToCart([FromBody] AddCollectionOfPatchActionsViewModel viewModel)
            {
             ....
            }
```

my viewmodel is:
```

   public class AddCollectionOfPatchActionsViewModel 
        {
            [Required]
            [MinLength(1, ErrorMessage = "At least one patch must be added.")]
            public ICollection<AddPatchActionViewModel> Patches { get; set; }
            [Required]
            public int PatchSetId { get; set; }
        }


            /// <summary>        
            /// Model for adding a patch to the cart
            /// </summary>
            public class AddPatchActionViewModel : IValidatableObject
            {


                [Required]
                public int PatchId { get; set; }
                [Required]
                public PatchAction PatchAction { get; set; }
                [MinLength(10)]
                public string Remarks { get; set; }

                public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
                {
                    var results = new List<ValidationResult>();

                    if (PatchAction == PatchAction.NotAddressed)
                    {
                        results.Add(new ValidationResult("A 'Not Addressed' action cannot be added to a patchset.", new List<string> { "Remarks" }));
                    }
                    else if (PatchAction == PatchAction.Disapprove || PatchAction == PatchAction.Ignore)
                    {
                        if (String.IsNullOrEmpty(Remarks))
                        {
                            results.Add(new ValidationResult("When Action is Disapprove or Ignore, Remarks must be specified.", new List<string> { "Remarks" }));
                        }
                    }
                    return results;
                }
            }

```
...and my enum is:
```

    public enum PatchAction
    {
        Install=0,
        Disapprove=1,
        Ignore=2,
        NotAddressed=3
    }
```

When I post any other value than 0 for PatchAction, everything is gravy.

However, when I post the following JSON post:

`{"Patches":[{"PatchId":100,"PatchAction":0,"Remarks":null}],"PatchSetId":100} `

I get the following error:
```

fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to cast object of type 'System.Collections.Generic.List`1[Namespace.Controllers.PatchSetsController+AddPatchActionViewModel]' to type 'System.Array'.
      System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[Namespace.Controllers.PatchSetsController+AddPatchActionViewModel]' to type 'System.Array'.
         at System.ComponentModel.DataAnnotations.MinLengthAttribute.IsValid(Object value)
         at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)
         at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.DataAnnotationsModelValidator.Validate(ModelValidationContext validationContext)
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitEnumerableType()
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model)
         at Microsoft.AspNet.Mvc.ModelBinding.Validation.DefaultObjectValidator.Validate(IModelValidatorProvider validatorProvider, ModelStateDictionary modelState, ValidationStateDictionary validationState, String prefix, Object model)
         at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<BindModelAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<PopulateArgumentsAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.DefaultControllerActionArgumentBinder.<BindActionArgumentsCoreAsync>d__5.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllActionFiltersAsync>d__52.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeExceptionFilterAsync>d__51.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.ApplicationInsights.AspNet.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
```

The odd thing is, this only ever happens with a value of 0.

**Comment by Yablargo** [comment]
I'm using the following deps:


  "dependencies": {    
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.InMemory": "7.0.0-rc1-final",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204",
    "Microsoft.AspNet.TestHost": "1.0.0-rc1-final",
    "Microsoft.AspNet.Identity": "3.0.0-rc1-final"
  },

**Comment by Yablargo** [comment]
If I change my viewmodel to be an array, and not an ICollection like so, I see no such error.

```
 public class AddCollectionOfPatchActionsViewModel 
        {
            [Required]
            [MinLength(1, ErrorMessage = "At least one patch must be added.")]
            public AddPatchActionViewModel[] Patches { get; set; }
            [Required]
            public int PatchSetId { get; set; }
        }
```

**Comment by Eilon** [comment]
@dougbu any thoughts on this? Maybe we fixed something in RC2 related to this?

**Comment by rynowak** [comment]
I'll bet :money_with_wings:  `MinLengthAttribute` casts the value to an array.

**Comment by dougbu** [comment]
Yeah @rynowak wins. Everything would be fine when using .NET Core (see that [`MinLengthAttribute` implementation](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MinLengthAttribute.cs#L66-L77)). `List<T>` implements both `ICollection<T>` and `ICollection` so all is well.

However the desktop .NET implementation is more like
``` c#
			string text = value as string;
			int length;
			if (text != null)
			{
				length = text.Length;
			}
			else
			{
				length = ((Array)value).Length;
			}
```

No `ICollection` case, no joy.

**Comment by dougbu** [comment]
> The odd thing is, this only ever happens with a value of `0`.

I'm betting this is because JSON.Net considers `0` as invalid -- not meeting the `[Required]` constraint. When using `AddPatchActionViewModel[]`, is the model valid? Or are there errors in the `ModelState`?

@Yablargo also please confirm this failure occurs when using desktop .NET.

**Comment by Eilon** [comment]
@dougbu anything that we can/should do to fix/work around this?

**Comment by Yablargo** [comment]
@doubgu That may be, I just think it is odd when the default enum value will be 0, thus this will be considered invalid. Interestingly, the issue goes away when I use an array instead of a List<> in my model.

I'll create a test project on 4.6.1 later and report back.

**Comment by dougbu** [comment]
@Eilon nothing leaps to mind. We don't do anything w/ the `[Required]` attribute before executing the `MinLengthAttribute.IsValid()` method. And we defer everything about instantiating the `AddCollectionOfPatchActionsViewModel` instance to JSON.Net.

@Yablargo what framework were you using when you hit the problem?

> I just think it is odd when the initial `enum` value will be `0`, thus this will be considered invalid.

I don't know how JSON.Net deals with value typed-properties that have associated `[Required]` attributes. Does the issue also go away if you remove that attribute from the `PatchAction` property?

**Comment by Yablargo** [comment]
@dougbu "Microsoft.AspNet.Mvc": "6.0.0-rc1-final", and dnxcore rc1

**Comment by dougbu** [comment]
I guess the CoreFx version of `[MinLength]` only recently added `ICollection` support. You'll be able to use your favourite types in RC2.

Bit surprised that removing the `[Required]` attribute doesn't change anything. Could you check the following:
> When using `AddPatchActionViewModel[]`, is the model valid? Or are there errors in the `ModelState`?

**Comment by Eilon** [comment]
@dougbu any further investigation left to do here?

**Comment by dougbu** [comment]
@Eilon not really. We know the exception is coming from CoreFx. The rest of my questions were primarily about recommending the best workaround.

But @Yablargo I would now recommend upgrading to RC2. That will get you a `[MinLength]` implementation that handles all `ICollection`s.

**Comment by Eilon** [comment]
Closing for now. If you have any further questions please let us know!
