### ISSUE TITLE
Fix functional tests that rely on views so they succeed when run in VS

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4543]
Currently 169 functional tests fail if executed from within VS. The error seems to always be some variant of the following (modulo static file resolution instead of searching for views):
```
Test Name:	AntiforgeryTests.Antiforgery_HeaderNotSet_SendsBadRequest
Test FullName:	Microsoft.AspNetCore.Mvc.FunctionalTests.AntiforgeryTests.Antiforgery_HeaderNotSet_SendsBadRequest
Test Source:	C:\dd\dnx\MVC\test\Microsoft.AspNetCore.Mvc.FunctionalTests\AntiforgeryTests.cs : line 123
Test Outcome:	Failed
Test Duration:	0:00:01.179

Result StackTrace:	
at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations) in C:\dd\dnx\MVC\src\Microsoft.AspNetCore.Mvc.ViewFeatures\ViewEngines\ViewEngineResult.cs:line 97
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext() in C:\dd\dnx\MVC\src\Microsoft.AspNetCore.Mvc.ViewFeatures\ViewResult.cs:line 70
...
The view 'Login' was not found. The following locations were searched:
/Views/Antiforgery/Login.cshtml
/Views/Shared/Login.cshtml
```

These tests used to work but started failing as we transitioned to the .NET CLI. The likely fix is in the `MvcTestFixture<TStartup>` class. Not clear relying on the current directory will work at all since VS probably doesn't guarantee it. (@vijayrkn does VS set the current directory before executing unit tests in an `.xproj` project?)

----

VS executes the following command:
```
"C:\Users\dougbu\AppData\Local\Microsoft\dotnet\dotnet.exe" test `
    "C:\dd\dnx\MVC\test\Microsoft.AspNetCore.Mvc.FunctionalTests\project.json" `
    -o "C:\dd\dnx\MVC\artifacts\bin\test\Microsoft.AspNetCore.Mvc.FunctionalTests\bin\Debug\netcoreapp1.0" `
    --port 58480 --parentProcessId 3848 --no-build
```

This is different from a command-line build. That instead executes two commands:
```
info: Exec
info:   program: dotnet
info:   commandline: test --configuration Debug
info:   workingdir: test\Microsoft.AspNetCore.Mvc.FunctionalTests

info: Exec
info:   program: C:\dd\dnx\MVC\.build\xunit.runner.console\2.1.0\tools\xunit.console.exe
info:   commandline: Microsoft.AspNetCore.Mvc.FunctionalTests.dll
info:   workingdir: test\Microsoft.AspNetCore.Mvc.FunctionalTests\bin\Debug\net451\win7-x64
```

**Comment by vijayrkn** [comment]
VS sets the directory containg project.json as the working directroy while executing the test.

**Comment by dougbu** [comment]
Thanks for fixing this in #4673.

**Comment by dougbu** [comment]
Marked as Working and moved into this milestone.
