### ISSUE TITLE
input TagHelper inside a lable TagHelper

### ISSUE THREAD

**Issue by John0King** [aspnet/Mvc#4749]
This is the default template of mvc core  
```razor
<div class="checkbox">
      <label asp-for="RememberMe">
               <input asp-for="RememberMe" />
               @Html.DisplayNameFor(m => m.RememberMe)
       </label>
</div>
```
This Code can run by default ,but when i change ViewModel's Display name
```C#
public class LoginViewModel
    {
       // some code 
       //******
        [Display(Name = "记住我?")]  // change "Remember me?" to "记住我?"
        public bool RememberMe { get; set; }
    }
```
then it throw a exception
```
System.NotImplementedException: The method or operation is not implemented.

   at Microsoft.AspNetCore.Razor.TagHelpers.DefaultTagHelperContent.EmptyOrWhiteSpaceWriter.Write(Char value)

   at System.Text.Encodings.Web.TextEncoder.Encode(TextWriter output, String value, Int32 startIndex, Int32 characterCount)

   at Microsoft.AspNetCore.Mvc.Rendering.TagBuilder.AppendAttributes(TextWriter writer, HtmlEncoder encoder)

   at Microsoft.AspNetCore.Mvc.Rendering.TagBuilder.WriteTo(TextWriter writer, HtmlEncoder encoder)

   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.WriteTo(TextWriter writer, HtmlEncoder encoder)

   at Microsoft.AspNetCore.Razor.TagHelpers.DefaultTagHelperContent.IsEmptyOrWhiteSpaceCore(Object entry, EmptyOrWhiteSpaceWriter writer)

   at Microsoft.AspNetCore.Razor.TagHelpers.DefaultTagHelperContent.get_IsEmptyOrWhiteSpace()

   at Microsoft.AspNetCore.Mvc.TagHelpers.LabelTagHelper.<ProcessAsync>d__15.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

```

*MVC Version*
"Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final"

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Razor/issues/760.
