### ISSUE TITLE
BadImageFormatException when rendering page

### ISSUE THREAD

**Issue by martincostello** [aspnet/Mvc#4781]
I've been working on a small application purely as an exercise in getting to grips with ASP.NET Core in [this project](https://github.com/martincostello/api).

I've deployed the latest commit ([9a93948fd98141fab2384d46c8c2b20280a1b019](https://github.com/martincostello/api/commit/9a93948fd98141fab2384d46c8c2b20280a1b019)) to an Azure WebApp running in both North Europe and East US behind Azure Traffic Manager from Visual Studio using the publish command. Both are configured to run as 64-bit applications in the Azure Portal.

The instance in North Europe is running correctly, however the instance in East US is failing with the stack trace below from the developer exception page.

From looking at Kudu, as far as I can tell, both WebApps are identically configured (except for their hostname), so I don't understand how the ```BadImageFormatException``` is occurring. I've pulled the contents of the sites out over FTP and compared them in Beyond Compare, and they are identical.

Is this a bug in MVC, the core framework or Azure Web Apps with RC2?

```
System.BadImageFormatException: Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'System.ComponentModel.TypeConverter, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelMetadata.InitializeTypeInformation()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata..ctor(IModelMetadataProvider provider, ICompositeMetadataDetailsProvider detailsProvider, DefaultMetadataDetails details)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreateModelMetadata(DefaultMetadataDetails entry)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreateCacheEntry(ModelMetadataIdentity key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.GetMetadataForType(Type modelType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ModelMetadataProviderExtensions.GetModelExplorerForType(IModelMetadataProvider provider, Type modelType, Object model)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(IModelMetadataProvider metadataProvider, ModelStateDictionary modelState, Type declaredModelType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionaryControllerPropertyActivator.GetViewDataDictionary(ControllerContext context)
   at Microsoft.Extensions.Internal.PropertyActivator`1.Activate(Object instance, TContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionaryControllerPropertyActivator.Activate(ControllerContext actionContext, Object controller)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.CreateInstance()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllActionFiltersAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeExceptionFilterAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by pranavkm** [comment]
Maybe this is the result of a bad native cache. cc @victorhurdugaci \ @davidebbo. any ideas what might be wrong here?

**Comment by davidebbo** [comment]
Note that we don't have the native cache yet on Web Apps. All we have is the shared fx in `D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002702`.

Also, please note that we only have 32 bit core fx. Configuring as 64 bit in the Azure portal only affects the w3wp.exe process, and since Core runs out of proc that doesn't apply to it.

But it's certainly quite strange that only one of the sites sees this if the content of their `site\wwwroot` folders is identical.

**Comment by martincostello** [comment]
I think I've gotten to the bottom of this. Looking at the FTP folder of the bad instance, it had a folder ```ftps://{azuredomain}/site/approot``` which contained the RC1 Update 1 runtime dated from March, which presumably got there from publishing a previous version of this app with Visual Studio after RC1 was released, which was then being picked up by something (is this folder in the ```PATH``` in Azure?).

Deleting the folder has resolved the problem.

Is this possibly a gap in the RC1 to RC2 migration advice after the content layout in IIS changed?

**Comment by davidebbo** [comment]
Yes, there are probably issues in the deployment process when moving from a deployed RC1 to RC2 site. It's so different that I'd suggest starting clean :)
