### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json after upgrading from RC2 to 1.0.0

### ISSUE THREAD

**Issue by gdoron** [aspnet/Mvc#4934]
Hi,

I'm trying to upgrade an rc2 application to 1.0.0 but getting errors on bootstraping the app  that Newtonsoft 7 & 8 do not exist.

![image](https://cloud.githubusercontent.com/assets/6141009/16484292/232e8ed8-3ec1-11e6-8765-938029af3861.png)

Stack trace:

>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Yooocan.Web.Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.<>c__DisplayClass4_0.b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

project.json file:

	  {
	    "userSecretsId": "aspnet-Yooocan-da7d67f5-45a8-4598-babb-cf9968743629",
	
	    "dependencies": {
	      "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
	      "Microsoft.AspNetCore.Diagnostics": "1.0.0",
	      "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
	      "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
	      "Microsoft.AspNetCore.Mvc": "1.0.0",
	      "Microsoft.AspNetCore.Razor.Tools": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
	      "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
	      "Microsoft.AspNetCore.StaticFiles": "1.0.0",
	      "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
	      "Microsoft.EntityFrameworkCore.Tools": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
	      "Microsoft.Extensions.Configuration.Json": "1.0.0",
	      "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
	      "Microsoft.Extensions.Logging": "1.0.0",
	      "Microsoft.Extensions.Logging.Console": "1.0.0",
	      "Microsoft.Extensions.Logging.Debug": "1.0.0",
	      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
	      "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Yooocan.Entities": "1.0.0-*",
	      "Yooocan.Logic": "1.0.0-*",
	      "AutoMapper": "5.0.0",
	      "Serilog.Sinks.Seq": "2.0.0",
	      "Serilog.Extensions.Logging": "1.0.0",
	      "Serilog": "2.0.0",
	      "Microsoft.AspNet.WebApi.Client": "5.2.3",
	      "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0",
	      "Microsoft.AspNetCore.Authentication.Google": "1.0.0",
	      "Microsoft.Azure.Search": "1.1.2",
	      "AspNet.Security.OAuth.LinkedIn": "1.0.0-alpha4-final"
	    },
	
	    "tools": {
	      "BundlerMinifier.Core": "2.0.238",
	      "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
	      "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
	      "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
	      "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
	      "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
	        "version": "1.0.0-preview2-final",
	        "imports": [
	          "portable-net45+win8"
	        ]
	      }
	    },
	
	    "frameworks": {
	      "net461": {
	      }
	    },
	
	    "buildOptions": {
	      "emitEntryPoint": true,
	      "preserveCompilationContext": true
	    },
	
	    "runtimeOptions": {
	      "gcServer": true
	    },
	
	    "publishOptions": {
	      "include": [
	        "wwwroot",
	        "Views",
	        "appsettings.json",
	        "web.config"
	      ]
	    },
	
	    "scripts": {
	      "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
	      "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
	    }
	 }

**Comment by bragma** [comment]
I've had similar problems, solved by deleting the project.lock.json file (it's recreated automatically)

**Comment by gdoron** [comment]
@bragma that didn't help :(
A. Is there a way of checking who requires these DLLs?
B. Is there a way of using <DependentAssembly> like in ASP.NET?

**Comment by gdoron** [comment]
@Eilon Is there any information other info I give provide?
I'm clueless what the issue can be.

I'm reverting back to RC-2.

**Comment by gdoron** [comment]
`<panic>`
Reverting to RC-2 (changed branch) didn't work, still got the same error, but instead of 7 & 8 being missing, it was 9.
I deleted the entire repository from my computer, and cloned it again from GitHub.
`</panic>`
Now my 1.0.0 branch works.

What is the reason for that odd issue? There're files who are not tracked by GitHub (not project.lock.json sinceI deleted them) that caused this.

I didn't checkout the rc-2 branch, since my entire team got stuck on this, we don't have the time to keep on playing with this. :disappointed:

**Comment by javiercn** [comment]
It's a known issue on the CLI. Under some circumstances it creates the wrong binding redirects. Cleaning the repository (git clean) and building should fix it, we inly observed it on update scenarios if you see it happening elsewhere let us know.

/cc @NTaylorMullen

**Comment by gdoron** [comment]
@javiercn thanks for the feedback.
Where are these generated files?

Anyway, it works fine now on my local machine, and when deployed the app (now 1.0.0) to Azure Web App, we get this error:

	System.InvalidOperationException: Can not find assembly file Microsoft.CodeAnalysis.CSharp.Workspaces.dll at 'D:\home\site\wwwroot\refs,D:\home\site\wwwroot\'
	   at Microsoft.Extensions.DependencyModel.Resolution.AppBaseCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
	   at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
	   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
	   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
	   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
	   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.GetCompilationReferences()
	   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.get_CompilationReferences()
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
	   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
	   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
	   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
	   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
	   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__32.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultFilterAsync>d__31.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllResultFiltersAsync>d__29.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
	   
Any hint about that?

**Comment by javiercn** [comment]
Looks like its related to Razor compilation. @pranavkm will know better

**Comment by gdoron** [comment]
@javiercn @pranavkm There's a bug with WebDeploy.
After contacting Azure support I manage to fix the missing stuff (totally random sh*t).
Wasted so much time on this. :cry:

**Comment by gdoron** [comment]
@NTaylorMullen is there an open issue for the CLI bug?
I would like to track it if it exists.

Thanks.

**Comment by NTaylorMullen** [comment]
@gdoron https://github.com/dotnet/cli/issues/3415
