### ISSUE TITLE
Unable to unit testing a controller on .net core 1.0

### ISSUE THREAD

**Issue by rguerreiro** [aspnet/Mvc#5140]
I'm trying to unit test the following controller:
```
namespace Application1.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        private readonly IAntiforgery _antiforgery;

        public HomeController(IAntiforgery antiforgery)
            : base()
        {
            _antiforgery = antiforgery;
        }

        public IActionResult Index()
        {
            var tokens = _antiforgery.GetAndStoreTokens(HttpContext);
            Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions() { HttpOnly = false });

            return View();
        }
    }
}
```
This is my test:
```
namespace Application1.Test
{
    public abstract class BaseTest
    {
        public BaseTest()
        {
            var services = new ServiceCollection();

            services.AddEntityFrameworkInMemoryDatabase()
                .AddDbContext<ApplicationDbContext>(options => options.UseInMemoryDatabase());

            InitServices(services);

            ServiceProvider = services.BuildServiceProvider();

            HttpContext = Substitute.For<HttpContext>();
            HttpContext.Request.Returns(Substitute.For<HttpRequest>());
            HttpContext.Response.Returns(Substitute.For<HttpResponse>());
        }

        protected virtual void InitServices(ServiceCollection services)
        {
            // do nothing
        }

        protected virtual void InitController(Controller controller)
        {
            controller.ControllerContext = new ControllerContext(
                new ActionContext(HttpContext, new RouteData(), new ControllerActionDescriptor())
            );
        }

        protected IServiceProvider ServiceProvider { get; set; }

        protected HttpContext HttpContext { get; set; }
    }

    public class HomeControllerTest : BaseTest
    {
        protected override void InitServices(ServiceCollection services)
        {
            services.AddMvc();
        }

        [Fact]
        public void Index_ReturnView()
        {
            // Arrange
            var antiForgeryMock = Substitute.For<IAntiforgery>();
            antiForgeryMock.GetAndStoreTokens(HttpContext).Returns(new AntiforgeryTokenSet("request token", "cookie token", "field", "header"));

            var controller = new HomeController(antiForgeryMock);
            InitController(controller);

            // Action
            var result = controller.Index();

            // Assert
            var viewResult = result.ShouldBeOfType<ViewResult>();
            viewResult.ViewName.ShouldNotBeNullOrEmpty();
        }
    }
}
```

But when in the `HomeController` when executing the line `return View();` on the `Index()` action it throws this exception:
```
System.InvalidOperationException : No service for type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ITempDataDictionaryFactory' has been registered.
      Stack Trace:
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
           at Microsoft.AspNetCore.Mvc.Controller.get_TempData()
           at Microsoft.AspNetCore.Mvc.Controller.View(String viewName, Object model)
```

Since the [docs for unit testing the controllers](https://docs.asp.net/en/latest/mvc/controllers/testing.html) are outdated I don't have a way to check if what I'm doing is right or not.

**Comment by pranavkm** [comment]
Have you tried adding Mvc to the service collection - `services.AddMvc()`?

**Comment by rguerreiro** [comment]
It's up there on my code...didn't you noticed it? In the `HomeControllerTest` on the `InitServices` method.

**Comment by rynowak** [comment]
There isn't anything I can see in the test code that's wiring up the service provider to your `HttpContext`.

The other issue that you might run into when you solve that is that your service provider will be a 'root' service provider not a 'scoped' service provider. If you need to get past that, resolve the `IServiceScopeFactory` and create a scoped provider from that.

Have you considered just mocking the properties that you need on controller? It should be possible to create a mock `ITempDataDictionary` and assign that property.

**Comment by rguerreiro** [comment]
> There isn't anything I can see in the test code that's wiring up the service provider to your `HttpContext`.

That's exactly what was missing. Thanks for the help.

Regarding your suggestions I did noticed that and already changed.

**Comment by moorthi-n** [comment]
any updates on this issue?.. seems like there is no resolution but this issue is already closed?.

**Comment by moorthi-n** [comment]
If anyone is still dealing with the issue Microsoft.AspNetCore.Mvc.ViewFeatures.ITempDataDictionaryFactory.
You will have to setup the TempData mock when instating the controller.
here is the solution.

         Mock<ITempDataDictionary> tempData = new Mock<ITempDataDictionary>();
            _subject = new XController(antiForgeryMock)
            {
                TempData = tempData.Object
            };
