### ISSUE TITLE
ASP.NET MVC AntiforgeryToken missing issue

### ISSUE THREAD

**Issue by kyajiv** [aspnet/Mvc#5263]
AntiforgeryToken doesn't work if user browse the website using googleweblight.

System.Web.Mvc.HttpAntiForgeryException (0x80004005): The required anti-forgery form field "__RequestVerificationToken" is not present.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext)
   at System.Web.Helpers.AntiForgery.Validate()
   at System.Web.Mvc.ValidateAntiForgeryTokenAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

**Comment by davidfowl** [comment]
System.Web.Mvc.HttpAntiForgeryException - This is not an ASP.NET Core issue.

**Comment by Eilon** [comment]
We'll move this to the right repo.

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetWebStack#48

**Comment by Eilon** [comment]
FYI the new AspNetWebStack repo isn't public yet, but it will be soon.
