### ISSUE TITLE
Inconsistent behavior disposing a Custom Razor View in Linux vs Windows

### ISSUE THREAD

**Issue by mythz** [aspnet/Mvc#5396]
I'm using [this technique mentioned in this issue](https://github.com/aspnet/Mvc/issues/3091) to render an MVC View without using an MVC Controller using code from [RazorFormat.cs](https://github.com/ServiceStack/ServiceStack/blob/34e65d0ab05200b0112085791b638df4e71ef2fc/src/ServiceStack.Mvc/RazorFormat.cs#L180):

```csharp
var actionContext = new ActionContext(
    ((HttpRequest) req.OriginalRequest).HttpContext,
    new RouteData(),
    new ActionDescriptor());

using (var sw = new StreamWriter(req.Response.OutputStream))
{
    if (viewData == null)
        viewData = CreateViewData((object)null);

    viewData[Keywords.IRequest] = req;
    var viewContext = new ViewContext(
        actionContext,
        view,
        viewData,
        new TempDataDictionary(actionContext.HttpContext, tempDataProvider),
        sw,
        new HtmlHelperOptions());

    view.RenderAsync(viewContext).GetAwaiter().GetResult();

    using (razorView?.RazorPage as IDisposable) {} //throws when running on Linux
}
```

In pages where I'm using [a Custom ViewPage I need to Dispose of Resources](https://github.com/ServiceStack/ServiceStack/blob/34e65d0ab05200b0112085791b638df4e71ef2fc/src/ServiceStack.Mvc/RazorFormat.cs#L465) used on that page. On Windows `Dispose()` doesn't get called so I have to call it explicitly but on Linux the same code throws the Exception below:

### Exception Message:

```
Cannot access a disposed object.
Object name: 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope
```

### StackTrace

```
>   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.GetPage(Int32 pageSize)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.GetCurrentPage()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.AppendHtml(String encoded)
   at AspNetCore._wwwroot_notfound_cshtml.&lt;&gt;c__DisplayClass28_0.&lt;&lt;ExecuteAsync&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.&lt;GetChildContentAsync&gt;d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.&lt;ProcessAsync&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.&lt;RunAsync&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._wwwroot_notfound_cshtml.&lt;ExecuteAsync&gt;d__28.MoveNext() in /wwwroot/notfound.cshtml:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.&lt;RenderPageAsync&gt;d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.&lt;RenderAsync&gt;d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceStack.Mvc.RazorFormat.RenderView(IRequest req, ViewDataDictionary viewData, IView view, String layout) in /opt/lib/teamcity-agent/work/d09206570215629/src/ServiceStack.Mvc/RazorFormat.cs:line 180
```

It would also be nice that the `RazorView` implemented `IDisposable` so custom Views can implement `Dispose()` and the Razor Page could automatically be disposed for us.

**Comment by dougbu** [comment]
What is the exact `@inherits` directive in your view? How are you setting `razorView` in your action -- `razorView = view as RazorView;`?

It's possible the `RazorPage` property has an unexpected value. Have you debugged and confirmed the value is a `ViewPage<T>` subclass?

**Comment by mythz** [comment]
This is an example of a page throwing this error [notfound.cshtml](https://github.com/NetCoreApps/RazorRockstars/blob/master/src/RazorRockstars.WebHost/wwwroot/notfound.cshtml) it doesn't have an `@inherits` directive however it uses [_ViewImports.cshtml](https://github.com/NetCoreApps/RazorRockstars/blob/master/src/RazorRockstars.WebHost/wwwroot/_ViewImports.cshtml) contained in the same directory which inherits this [custom ViewPage<T>](https://github.com/ServiceStack/ServiceStack/blob/59913993f44d84efa51245596a0ba18281421831/src/ServiceStack.Mvc/RazorFormat.cs#L403)

Here's a live example of the error which gets executed when a page doesn't exist: http://razor.netcore.io/thispagedoesnotexist

This route works without issue on Windows.

**Comment by pranavkm** [comment]
Are you reusing the view or using it concurrently - https://github.com/ServiceStack/ServiceStack/blob/34e65d0ab05200b0112085791b638df4e71ef2fc/src/ServiceStack.Mvc/RazorFormat.cs#L210?

**Comment by mythz** [comment]
No that code only [resolves the view from IRazorViewEngine.GetView()](https://github.com/ServiceStack/ServiceStack/blob/34e65d0ab05200b0112085791b638df4e71ef2fc/src/ServiceStack.Mvc/RazorFormat.cs#L84) and [gets executed](https://github.com/ServiceStack/ServiceStack/blob/34e65d0ab05200b0112085791b638df4e71ef2fc/src/ServiceStack.Mvc/RazorFormat.cs#L71) once per request.

**Comment by pranavkm** [comment]
Not super sure how your Requests are wired up - but is the `IServiceProvider` on `ActionContext.HttpContext.RequestServices` an instance of `IServiceProvider` from `IServiceScopeFactory`? You have to do some extra work to wire the right service provider if you aren't in the context of a regular middleware pipeline - https://github.com/aspnet/Mvc/issues/5106#issuecomment-237123139

**Comment by mythz** [comment]
Had a chance to revisit this again today, the issue was as you expected, from a separate code path which was reusing and disposing the same `viewEngineResult` instance which would throw this Exception after the first request. Changing it to fetch a new `viewEngineResult` on each request resolved the issue.

Many thanks for your help!
