### ISSUE TITLE
ViewsFeatureProvider and dynamic assemblies

### ISSUE THREAD

**Issue by mdschweda** [aspnet/Mvc#5487]
```csharp
protected virtual Type GetViewInfoContainerType(AssemblyPart assemblyPart)
{
    if (assemblyPart.Assembly.Location != null)
    {
        // ...
    }
    // ...
}
```
in `ViewFeaturesProvider` fails when adding dynamic assemblies via `IMvcBuilder.AddApplicationPart` (`System.Reflection.Emit.AssemblyBuilder.Location` throws `NotSupportedException`). Here is a stack trace:

```
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.ViewsFeatureProvider.GetViewInfoContainerType(AssemblyPart assemblyPart)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.ViewsFeatureProvider.PopulateFeature(IEnumerable`1 parts, ViewsFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultCompilerCacheProvider..ctor(ApplicationPartManager applicationPartManager, IRazorViewEngineFileProviderAccessor fileProviderAccessor)
```

Would there be any major implications when checking if `assemblyPart.Assembly.IsDynamic` before trying to retrieve its location? Am I missing something when working with dynamic assemblies in projects with  controllers returning views?

**Comment by pranavkm** [comment]
> Would there be any major implications when checking if assemblyPart.Assembly.IsDynamic before trying to retrieve its location?

That sounds fine. I recall trying out loading a Roslyn generated assembly and it didn't throw when `Location` was accessed. Would you like to send a pull request for this?

**Comment by mdschweda** [comment]
Sure
