### ISSUE TITLE
Cannot start 1.1 website on 2008R2

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Mvc#5550]
The website runs well on W10 and WS2012, however it looks impossible to start it from WS2008R2. Another website (V1.0) is running well on the 2008R2 server, and the same website (before migration) also runs well. The 1.1 version returns "HTTP Error 502.5 - Process Failure"

The website uses EFCore and MS Identity and forces SSL (in startup.cs).

I have been trying to uninstall/reinstall all the frameworks and tools, but I always get the same error!
(I tried to add the System.Text.Encodings.Web required, however the exact version is not available on NuGets)

Here is the stdout exception logged:
    
    Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
       at Microsoft.Extensions.DependencyInjection.EncoderServiceCollectionExtensions.AddWebEncoders(IServiceCollection services)
       at Microsoft.Extensions.DependencyInjection.AuthenticationServiceCollectionExtensions.AddAuthentication(IServiceCollection services)
       at Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions.AddIdentity[TUser,TRole](IServiceCollection services, Action`1 setupAction)
       at Website.Startup.ConfigureServices(IServiceCollection services) in Z:\Website\Startup.cs:line 78
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
    
    Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
       at Microsoft.Extensions.RazorViews.BaseView..ctor()
       at Microsoft.AspNetCore.Hosting.Views.ErrorPage..ctor(ErrorPageModel model)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at Website.Program.Main(String[] args) in Z:\Website\Program.cs:line 14
    
This is the stdout log from IIS 7.5. I get the same error when launching directly from command line.

**Comment by JeanCollas** [comment]
Ok, I can make it work by publishing it manually via cmd

    dotnet.exe publish "Z:\Website\" --framework netcoreapp1.1 --output "z:\bin\debug\tempWebsite" --configuration Debug

However the full publishing process of Visual Studio creates a website that still has the same issue.
Are there operations that would need to be updated?

**Comment by Eilon** [comment]
@JeanCollas can you compare the command line that VS uses for its publishing and the one that you used successfully? I believe if you look in VS's output window (or some other similar window) you can see the commands it ran.

**Comment by JeanCollas** [comment]
@Eilon I have solved this issue somehow now, I cannot give more details. However the command line was the same, as I took it from VS output :)

**Comment by Eilon** [comment]
Ok!
