### ISSUE TITLE
Model binding, BindNeverAttribute and BindAttribute ignored ? 

### ISSUE THREAD

**Issue by Socolin** [aspnet/Mvc#5633]
Hi,

I have a model with some "get properties" depending on other properties of the model

```
        public Group Group => Device.Group;
```

These properties are not meant to be binded but its seems they are accessed during binding process. So in my case I got a crash due to a null exception. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at XXXXXXX.XXXXXXModel.get_Group() in /XXXXX/XXXXModel.cs:line 44
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultComplexObjectValidationStrategy.Enumerator.MoveNext()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindModelAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindArgumentsCoreAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
Object reference not set to an instance of an object.
```

I tried to add `[BindNever]` on the property, and I also try `[Bind("List","Of","Property","To","Bind")]` on the model but I still get this error.

How can I fix this without adding check on every get property to handle this case ?

**Comment by Eilon** [comment]
@rynowak @dougbu I assume the validation system always runs on everything, regardless of whether it was bound, right? I think we've had requests in the past to disable validation on model properties, does that sound familiar to you?

**Comment by rynowak** [comment]
Correct, there is no way to prevent the validation system from traversing a *specific property*. You can prevent the validation system from traversing any property of a given class.

In general this is because we have a model validation system not an input validation system - it's working to ensure that a dedicated model object is in a valid state.

http://bradwilson.typepad.com/blog/2010/01/input-validation-vs-model-validation-in-aspnet-mvc.html Much of what Brad wrote about this long ago is still true.

**Comment by dougbu** [comment]
@Socolin why is `Device` null in your test?

@rynowak 
> there is no way to prevent the validation system from traversing a _specific_ property.

I agree. The `DefaultComplexObjectValidationStrategy` gets the value of every property that's `public` and gettable.

On the other hand, if other properties don't need validation, it is simple to suppress validation of the entire class containing the `Group` property e.g.
``` c#
options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Container)));
```
Not exactly what @Socolin wants of course.

**Comment by Eilon** [comment]
Related: https://github.com/aspnet/Mvc/issues/4143

**Comment by Socolin** [comment]
@dougbu Device is null because it's an helper to get access to an object created depending of the input, and loaded in database with permissions check. After validating model I call a method to do the job (I planned to do it automatically in an filter), then I can use one of the helper to access to the created object as IDevice or as a derived class with custom exception if cast failed to have a simple and understanding message of what is wrong in this case. In my case if the bindings properties could be "private" it would be good.

**Comment by Eilon** [comment]
@Socolin yep your scenario totally makes sense. We'll look at adding some feature to help make this a lot easier. It would likely be some new attribute, i.e. `[ValidateNever]`, which specifically disables validation on a specific property (or perhaps even a type).

We wouldn't build this into the `[BindNever]` attribute because that would be a huge breaking change, and also there are cases where you might not bind a property, yet use it for object-level validation (probably not super common, though).
