### ISSUE TITLE
JSonInputFormatter throws two exceptions when I receive invalid json as JObject

### ISSUE THREAD

**Issue by PiotrPerak** [aspnet/Mvc#5970]
Given the input
<pre>{
   scheduleType: "simple",
   scheduleDetail: {
       RepeatInterval: "0.01:00:00.0000"
   },
   arguments: {
		   AgeHours: 7,
		   TransStatus: a,
		   PersonUserID: "CENTRALADMIN"
   },
   description: 333
}</pre>

I get this back
<pre>{
  "arguments.TransStatus": [
    "The input was not valid.",
    "The input was not valid."
  ]
}</pre>

In my model I receive `arguments` as `JObject` because it can be different with every request.
I enabled logging in MVC and I see exception thrown twice.
<pre>2017-03-15 16:30:26.8313|DEBUG|Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter|JSON input formatter threw an exception.|Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: a. Path 'arguments.TransStatus', line 8, position 17.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2017-03-15 16:30:26.8453|DEBUG|Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter|JSON input formatter threw an exception.|Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: a. Path 'arguments.TransStatus', line 8, position 17.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.Skip()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(JsonReader reader, Boolean readPastError, Int32 initialDepth)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)</pre>

When I change value of `TransStatus` to 2a it tries to parse it as number and throws only one exception and one "The input was not valid." message in response. Stack trace is:
<pre>2017-03-15 16:37:01.8970|DEBUG|Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter|JSON input formatter threw an exception.|Newtonsoft.Json.JsonReaderException: Input string '2a' is not a valid number. Path 'arguments.TransStatus', line 8, position 19.
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)</pre>

I'm not sure if this is a bug or not. But I don't think returning same message twice is good.

**Comment by danroth27** [comment]
@kichalla Could you please try to reproduce this?

**Comment by kichalla** [comment]
@PiotrPerak I am unable to repro this issue in the 1.0.3, 1.1.2 and latest versions of MVC. Could you share a simple repro project?

**Comment by PiotrPerak** [comment]
```csharp
[HttpPost("{jobName}/trigger")]
    public async Task<IActionResult> Trigger(string jobName, [FromBody] JobArguments jobArgs)
    {
        if (!ModelState.IsValid || string.IsNullOrEmpty(jobName) || jobArgs == null)
             return BadRequest(ModelState);
        return Ok();
    }

    public class JobArguments
    {
        public JObject Arguments { get; set; }
    }```

**Comment by kichalla** [comment]
Thanks @PiotrPerak. I am able to repro it. We will get back to you regarding this.

I see that this issue happens outside the context of ASP.NET, for example here the error would be printed 2 times.

```c#
public class Program
{
    public static void Main(string[] args)
    {
        EventHandler<Newtonsoft.Json.Serialization.ErrorEventArgs> errorHandler = (sender, eventArgs) =>
        {
            Console.WriteLine(eventArgs.ErrorContext.Error.ToString());
            Console.WriteLine("-----------------------------");
            eventArgs.ErrorContext.Handled = true;
        };

        using (var streamReader = new StreamReader(File.OpenRead("input.txt")))
        {
            using (var jsonReader = new JsonTextReader(streamReader))
            {
                var jsonSerializer = new JsonSerializer();
                jsonSerializer.Error += errorHandler;
                var jobArgs = jsonSerializer.Deserialize<JobArguments>(jsonReader);
            }
        }
    }
}

public class JobArguments
{
    public JObject Arguments { get; set; }
}
```

input above was:
```
{
"arguments": {
    personUserId: "CENTRALADMIN",
	ageHours: 2,
	transStatus: a,
	userType: 2
	}
}
```

**Comment by kichalla** [comment]
@rynowak @dougbu what do you suggest we should be doing here?

**Comment by dougbu** [comment]
@kichalla I suggest we treat this issue as External and ensure the correct issue is filed in https://github.com/JamesNK/Newtonsoft.Json. The `JsonSerializerInternalReader.HandleError()` should be better-protected to avoid repeating the `Exception` that method is handling.

**Comment by kichalla** [comment]
Thanks @dougbu ...I filed here: https://github.com/JamesNK/Newtonsoft.Json/issues/1262
