### ISSUE TITLE
Test failure: The following constructor parameters did not have matching fixture data

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#6162]
http://aspnetci/viewLog.html?buildId=204864&tab=buildResultsDiv&buildTypeId=Lite_MvcTest
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Command exited unexpectedly with exit code: 255))
(The following constructor parameters did not have matching fixture data: ApplicationUsingRelativePathsTestFixture fixture)
---- System.AggregateException : One or more errors occurred. (Command exited unexpectedly with exit code: 255)
-------- System.Exception : Command exited unexpectedly with exit code: 255
---- The following constructor parameters did not have matching fixture data: ApplicationUsingRelativePathsTestFixture fixture

----- Inner Stack Trace #1 (System.AggregateException) -----
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.ApplicationTestFixture..ctor(String applicationName)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<StartSelfHostAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.<DeployAsync>d__7.MoveNext()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----v
```

**Comment by Tratcher** [comment]
Caused by https://github.com/dotnet/cli/issues/6318 ?

**Comment by pranavkm** [comment]
This was fixed by https://github.com/aspnet/MvcPrecompilation/issues/115, https://github.com/aspnet/Mvc/pull/6166
