### ISSUE TITLE
Exception when calling RedirectToPage("./Index") from a page with routed parameters

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6218]
I tried to create a simplified repro but failed, so here's directions to the app where it happens:

1. Clone https://github.com/DamianEdwards/RazorPagesSample
1. Open in VS and run the RazorPagesSample project
1. Navigate to http://localhost:1109/Customers/SeparatePageModels and create a customer
1. Edit the customer and click save

[This line](https://github.com/DamianEdwards/RazorPagesSample/blob/master/RazorPagesSample/Pages/Customers/SeparatePageModels/Edit.cshtml.cs#L58) throws, but only if the page gets the ID from the route, i.e. `@page "{id:int}"` instead of `@page`.
```
System.InvalidOperationException: No page named './Index' matches the supplied values.
   at Microsoft.AspNetCore.Mvc.Internal.RedirectToPageResultExecutor.Execute(ActionContext context, RedirectToPageResult result)
   at Microsoft.AspNetCore.Mvc.ActionResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<ExecutePageAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeInnerFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by DamianEdwards** [comment]
@pranavkm @rynowak

**Comment by rynowak** [comment]
We need to add the route values to this error message 👎

**Comment by DamianEdwards** [comment]
In step 4 above, just navigating to the Edit page results in the menu link URL generation not working. You get empty URLs. Something about the Edit page is messing up the routing URL stuff.

**Comment by Eilon** [comment]
@rynowak - can you investigate for Preview1?

**Comment by rynowak** [comment]
Yep. Looking now.

**Comment by rynowak** [comment]
aspnet/Razor@232b73a1516f7eae1d3a3697aabb2c1c7ffc530b
