### ISSUE TITLE
Using FormattingUtilities.XsdDataContractExporter.GetRootElementName(type) throws in netcoreapp2.0 when used in ExplicitResponseTypeDecoration_WithExplicitDefaultStatus_SpecifiedViaProducesAttribute

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6235]
```C#
Type 'Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.

   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.XsdDataContractExporter.GetRootElementName(Type type)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlDataContractSerializerOutputFormatter.CreateSerializer(Type type)
```

**Comment by pranavkm** [comment]
Here's the code to be inserted in `XmlDataContractSerializerOutputFormatter.CreateSerializer`:

```C#
                // Verify that type is a valid data contract by forcing the serializer to try to create a data contract
                FormattingUtilities.XsdDataContractExporter.GetRootElementName(type);
```

**Comment by rynowak** [comment]
We're not supposed to directly serialize MSD, that's what the serialization proxies are for.

**Comment by pranavkm** [comment]
Something in the code path is attempting to serialize it and it throws (which apparently worked on desktop?). Filed a bug so we can move on with the TFM conversion for the time being because we previously weren't calling this API from netcoreapp

**Comment by pranavkm** [comment]
Self-assigning to see if we missed something doing the TFM conversions.
