### ISSUE TITLE
AmbiguousMatchException in Html.TextBox() when model has shadowed properties

### ISSUE THREAD

**Issue by neoGeneva** [aspnet/Mvc#6946]
Calling `Html.TextBox()` for a property that is shadowing an inherited property, a AmbiguousMatchException exception is thrown.

For example, the following setup will generate the error:

### Models.cs
```csharp
namespace Test
{
    public class SearchBase
    {
        public string Search { get; set; }
    }

    public class SearchModel : SearchBase
    {
        public new int Search { get; }
    }
}
```

### Index.cshtml
```html
@model Test.SearchModel

@Html.TextBox("Search")
```

### HomeController.cs
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Test
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new SearchModel();

            return View(model);
        }
    }
}
```

### Generates the following exception:
```
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(Type type, String name)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataEvaluator.GetPropertyValue(Object container, String propertyName)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataEvaluator.InnerEvalComplexExpression(Object indexableObject, String expression)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataEvaluator.EvalComplexExpression(Object indexableObject, String expression)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataEvaluator.Eval(ViewDataDictionary viewData, String expression)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ExpressionMetadataProvider.FromStringExpression(String expression, ViewDataDictionary viewData, IModelMetadataProvider metadataProvider)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.AddPlaceholderAttribute(ViewDataDictionary viewData, TagBuilder tagBuilder, ModelExplorer modelExplorer, String expression)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateInput(ViewContext viewContext, InputType inputType, ModelExplorer modelExplorer, String expression, Object value, Boolean useViewData, Boolean isChecked, Boolean setId, Boolean isExplicitValue, String format, IDictionary`2 htmlAttributes)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateTextBox(ViewContext viewContext, ModelExplorer modelExplorer, String expression, Object value, String format, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.GenerateTextBox(ModelExplorer modelExplorer, String expression, Object value, String format, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.TextBox(String expression, Object value, String format, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperInputExtensions.TextBox(IHtmlHelper htmlHelper, String expression)
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__0.MoveNext() in C:\Users\Phil\AmbiguousMatchExceptionMvc\Views\Home\Index.cshtml:line 3
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Eilon** [comment]
Hi @neoGeneva , we decided a while ago to not support shadowed properties: https://github.com/aspnet/Mvc/issues/4646#issuecomment-219521703

It's not a common scenario and not recommended in general, so we chose not to support it. It introduces many complexities to the whole system and the system just wasn't designed for it.

**Comment by neoGeneva** [comment]
Hey @Eilon, thanks for letting me know, but if that is the case then surely are more relevant exception should be thrown? 

The "AmbiguousMatchException" doesn't really info necessary to fix the problem, it took me a little while to figure out exactly what was going on.

**Comment by Eilon** [comment]
@neoGeneva this is a fairly rare case, so we just haven't invested much time or effort into it, including error cases. If you can propose a fix for this it's something we'd consider taking.

**Comment by neoGeneva** [comment]
Hey @Eilon, that makes sense. 

Maybe something to revisit if more people raise the same issue, and even the the solution might be just to add something to the docs to mention that shadowed properties aren't supported, just so there's something more specific to point to.
