### ISSUE TITLE
Socket Exception on TryValidateModel in RazorPages

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Mvc#6989]
I have a very simple Razor Page I'm experimenting with and I'm having issues getting model state to validate. 

Basically I have a text box in form with a value that has a Validation attribute (MinLength) and I'm trying to get the model to validate. It doesn't happen automatically in OnPost so I'm using `TryValidateModel(this)` which throws a Socket Exception:

![image](https://user-images.githubusercontent.com/1374013/31917696-8cd225d6-b7f4-11e7-8e66-fd93f3cf0195.png)

The page is a very simple self-contained (no code behind model - but tried that with same behavior) razor page:
```razor
@page
@model IndexModel
@using System.ComponentModel.DataAnnotations
@using Microsoft.AspNetCore.Mvc.RazorPages
@functions {

    public class IndexModel : PageModel
    {
        [MinLength(2)]
        public string Name { get; set; }

        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Getting somewhere";
        }


        public void OnPost()
        {
            // do we need explicit validation? Shouldn't hte model auto-validate on POST
            TryValidateModel(this);

            // this is ALWAYS true
            if (this.ModelState.IsValid)
                Message = "Posted all clear!";
            else
                Message = "Posted no trespassing!";
        }

    }

}
@{    
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>    
</head>
<body>
<form method="post" asp-antiforgery="true">
    <input asp-for="Name" type="text" />
    <button type="submit" class="btn btn-default">Show Hello</button>
    @Model.Name
</form>

<div class="alert alert-warning">
    @Model.Message
</div>
</body>
</html>
```

#### More Observations
The page works otherwise and the model data (the message) display. The model is also updated properly - OnPost() has the model value set to the entered value. The problem isn't the binding it's the model validation that appears to be not working.

Entirely possible I'm missing something but I don't see it :-)

Two questions here:

* I would have expected OnPost to unbind the model automatically and give me ModelState I can work with. Not happening here. Not sure if it should.

* Why would TryValidateModelState() throw a Socket exception of all things?

Stack Trace:
```
   at System.Net.IPAddress.get_Address()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultComplexObjectValidationStrategy.Enumerator.GetModel(Object container, ModelMetadata property)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultComplexObjectValidationStrategy.Enumerator.<>c__DisplayClass10_0.<MoveNext>b__1()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultObjectValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model)
   at Microsoft.AspNetCore.Mvc.RazorPages.PageBase.TryValidateModel(Object model, String prefix)
   at Microsoft.AspNetCore.Mvc.RazorPages.PageBase.TryValidateModel(Object model)
   at AspNetCore._Pages_Test_cshtml.OnPost() in c:\projects2010\Conferences\AspNetCoreLocalization\AspNetCoreLocalization\Pages\Test.cshtml:line 22
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeHandlerMethodAsync>d__29.MoveNext()
```

**Comment by hishamco** [comment]
You could move your validation attributes to the `Model` instead

**Comment by hishamco** [comment]
But still I'm surprising why it throws Socket Exception?!! 
@rynowak any idea?

**Comment by rynowak** [comment]
> Why would TryValidateModelState() throw a Socket exception of all things?

Look at the call stack:
```
at System.Net.IPAddress.get_Address()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultComplexObjectValidationStrategy.Enumerator.GetModel(Object container, ModelMetadata property)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultComplexObjectValidationStrategy.Enumerator.<>c__DisplayClass10_0.<MoveNext>b__1()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
```

`TryValidateModel` will recursively access all of the properties of the the object you pass in to perform validation. Since you passed in a `PageModel`-derived class it's walking `PageModel`->`HttpContext`->`ConnectionInfo`->`Socket`->`IPAddress`. 

I assume that you're doing this because your `[MinLength(..)]` attribute is not getting run. Prior to 2.1 - MVC core does not support placing validation attributes directly on a top-level binding item (parameter or page/controller property). 

This feature has been added for 2.1.

You should create a class that represents your input and use that.
```
public class Person
{
    [MinLength(2)]
    public string Name { get; set; }
}

public class IndexModel : PageModel
    {
        public Person Person { get; set; }

        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Getting somewhere";
        }

...

<form method="post" asp-antiforgery="true">
    <input asp-for="Person.Name" type="text" />
    <button type="submit" class="btn btn-default">Show Hello</button>
    @Model.Person.Name
</form>
```

**Comment by hishamco** [comment]
Thanks for clarification @rynowak
