### ISSUE TITLE
Disabling antiforgery token verification for a single razor page's OnPost method

### ISSUE THREAD

**Issue by svallis** [aspnet/Mvc#7012]
Modifying the conventions for razor pages allows disabling of the antiforgery token verification globally:

```
services.AddMvc().AddRazorPagesOptions(options =>
{
    options.ConfigureFilter(new IgnoreAntiforgeryTokenAttribute());
});
```

I only have a single endpoint on my application that needs to disable this though. Adding `[IgnoreAntiforgeryToken]` anywhere potentially relevant doesn't seem to help. Is this situation supported or possible, or do I need to use an MVC controller to handle things?

**Comment by seanfisher** [comment]
Same problem here. Adding `[IgnoreAntiforgeryToken]` to the RazorPage class or method does not disable the check. Here's the log message, if it helps:

```
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.XXXXXXXXX" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.XXXXXXXXX" is not present.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter:Information: Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.XXXXXXXXX" is not present.

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.XXXXXXXXX" is not present.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter'.
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter'.
Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 400
Microsoft.AspNetCore.Mvc.StatusCodeResult:Information: Executing HttpStatusCodeResult, setting HTTP status code 400
```

Disabling the filter globally seems to be the only way to turn it off. I got @svallis's code to work with a sight modification:

```
services.AddMvc().AddRazorPagesOptions(options =>
{
    options.Conventions.ConfigureFilter(new IgnoreAntiforgeryTokenAttribute());
});
```

**Comment by svallis** [comment]
@seanfisher Decorate your `PageModel` class with `[IgnoreAntiforgeryToken(Order = 1001)]`. The key is the `Order` parameter. The built in `[ValidateAntiforgeryToken]` has an order of `1000`, and therefore explicitly setting `[IgnoreAntiforgeryToken]` to anything greater than `1000` should resolve the issue.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
