### ISSUE TITLE
Dictionary binding

### ISSUE THREAD

**Issue by pelhu** [aspnet/Mvc#7091]
Hello,
I have an error when post the following data to server

```
WorkerTypesCounts[ARCHIVE]:111
WorkerTypesCounts[CORRELATION]:222
WorkerTypesCounts[INDEX]:333
```

The error is 

```
 System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(KeyValuePair`2 keyValuePair)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.CopyToModel(Object target, IEnumerable`1 sourceCollection)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.<BindModelAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinder`2.<BindModelAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder.<BindModelCoreAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

But when I rename "INDEX" to "INDEX2" everything works fine

```
WorkerTypesCounts[ARCHIVE]:111
WorkerTypesCounts[CORRELATION]:222
WorkerTypesCounts[INDEX2]:333
```

**Comment by Eilon** [comment]
@dougbu any idea on this? Is `index` some kind of reserved term?

**Comment by dougbu** [comment]
> Is `index` some kind of reserved term?

Shouldn't be.

@pelhu do you have a small sample e.g. a project in a GitHub repo that I could clone then debug?

**Comment by pelhu** [comment]
> @pelhu do you have a small sample e.g. a project in a GitHub repo that I could clone then debug?

@dougbu sorry, it is in my enterprise project. But if you want i can prepare small project for debug.

**Comment by dougbu** [comment]
> But if you want i can prepare small project for debug.

That would be great @pelhu!

**Comment by pelhu** [comment]
> That would be great @pelhu!

Hi @dougbu here is project https://github.com/pelhu/MvcIssue7091

**Comment by dougbu** [comment]
Thanks for the project @pelhu!

:ok: this bug (and it is a bug) is due to the `CollectionModelBinder`'s workarounds for binding collections containing gaps or a subset of a submitted collection. The `"index"` key is interpreted as the collection of keys that should be bound.

In this case, model binding creates an interim `List<KeyValuePair<string, int?>>` and adds a `KeyValuePair<string, int?>` with `Key==null` and `Value==null` to that. The element binder failed but the collection binder added the "invalid" (for the dictionary case) element to fill an expected gap in the collection and allow the binder to find later errors. The `ArgumentNullException` occurs shortly after, while attempting to convert the list to the requested dictionary.

Possible fixes:
1. Use `"index"` only when binding collections of simple types e.g. not when binding `IEnumerable<KeyValuePair<string, int?>>`. This breaks down when the submitted values have names like `Dict[0].Key`, `Dict[1].Value`, &hellip; and you *do* want to skip some indices for some reason.
2. Use `"index"` unless binding a `Dictionary<TKey, TValue>`. This again breaks the `Dict[0].Key`, `Dict[1].Value`, &hellip; case 
2. Attempt to use `"index"` all the time but don't add anything to the collection when the element binder fails in the first iteration. If this check fails, the collection should be empty anyhow.
  a. Could limit this further and only skip the addition when the `"index"` appears to contain only one value.
3. Always stop binding collection elements on the first failure. This is the case already when not using `"index"`. However, doing this misses errors in the submitted `"index"` value.
4. Subset the `CompositeValueProvider` to remove the `JQueryFormValueProvider` while getting the `"index"` value. This would mean `Dict.index` (if submitted) would be used for index names but `Dict[index]` (what's submitted in this case) would not.
5. Add a `try` block in `DictionaryModelBinder` either around the `collection.ToDictionary(...)` call or the `base.BindModelAync(...)` call. The binder could then continue with its fallback binding approach. This may be useful in general when `TKey` is `string` but could also hide errors in the submitted data e.g. `Dict[0].Key=&Dict[0].Value=23`.

I lean toward (4) because it only restricts *syntax*, doesn't remove or narrow any features. I'm thinking (5) may also help but only to prevent the `Exception` for `Dict[0].Key=&Dict[0].Value=23` leaking out of the model binding system. (That's really a separate bug.)

@Eilon, @rynowak your thoughts?

----

Admittedly the choice of `"index"` for this special case isn't the best. The name needs to be relatively sensible but shouldn't have been such a common word. Even `"$index"` or similar would have been better. But, changing this now would be a significant breaking change.

**Comment by dougbu** [comment]
My counts were off. I've updated the references in my last paragraph before the break.

I've also prototyped (5) and found no tests at all fail with that in place. Not ready for a PR (need tests) but at least we know that option avoids this problem.

**Comment by dougbu** [comment]
@danroth27 @mkArtakMSFT this doesn't "need design" if others agree with my preferences above. But, more importantly, what milestone should I fix this in? Should fit in Preview1 if you think it's urgent. (Certainly ugly that the "index" key is busted.)

**Comment by dougbu** [comment]
Do something like (5) but avoid delving so deep below the exposed model binding abstractions. One idea is to add an `ICanHaveRewriteSemantics` that the jQuery value provider implements. Also add a new method that can filter out `ICanHaveRewriteSemantics` from the `CompositeValueProvider` (or its exposed list of providers).

Detect the `Dict[0].Key=&Dict[0].Value=23` case (`null` key due to empty-to-null conversion) explicitly in the `KeyValuePairModelBinder`. Make that a `ModelState` error.

**Comment by dougbu** [comment]
Now have design, removing label 😈

**Comment by dougbu** [comment]
And, thanks @rynowak !

**Comment by dougbu** [comment]
@mkArtakMSFT cost takes into account work I've already done on this issue

**Comment by dougbu** [comment]
390ebbb258 in `release/2.1`
1aeaf69f87 merges this to `dev`
