### ISSUE TITLE
FileStreamResult needs Read&Write permission?

### ISSUE THREAD

**Issue by muqeet-khan** [aspnet/Mvc#7150]
I am creating this issue because I am not sure if this was the case in previous versions, but, does FileStreamResult need read & write permission for IIS_IUSRS on the resource in order to be served?

**Environment**
Visual Studio - 15.5.2
AspNetCore - 2.0.3
Published to IIS 8.5

**Repro Project**
I have a simple repro project that you can use and publish to IIS at https://github.com/muqeet-khan/VideoProcessingSample . All this project provides is the below code and a sample BigBunny mp4 video.

1. I am not doing anything special. I am using` FileStreamResult` to serve a MP4.

```
         public IActionResult ServeVideo(string filename)
        {
            var fPath = Path.Combine(new string[] { "Media", filename });
            var fullPath = Path.Combine(_appEnvironment.ContentRootPath, "wwwroot\\" + fPath);
            return new FileStreamResult(new FileStream(fullPath, FileMode.Open), "video/mp4");
        }
```
2. Upload a video to the Media folder and make sure it has Read permissions only. 
3. After publishing to IIS,
http://IIS_Website/home/servevideo?filename=BigBuckBunny_320x180.mp4 -- Returns 500 with an exception.

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Access to the path 'MP4 Path' is denied.
System.UnauthorizedAccessException: Access to the path 'MP4 Path' is denied.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Sample.Controllers.HomeController.ServeVideo(String filename)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

However, http://IIS_Website/Media/BigBuckBunny_320x180.mp4 - **Static File Middleware** works just fine with just read permission.

4. Give Read and Write permissions on the media file for IIS_IUSRS and the file will be served by the ServeVideo Action just fine.

**Comment by benaadams** [comment]
Add `FileAccess.Read` as last param when creating the FileStream
```csharp
return new FileStreamResult(new FileStream(fullPath, FileMode.Open, FileAccess.Read), "video/mp4");
```

**Comment by benaadams** [comment]
You could use a `PhysicalFileResult` rather than the `FileStreamResult`+`FileStream`?

```csharp
return new PhysicalFileResult(fullPath, "video/mp4");
```
