### ISSUE TITLE
IFormFile.CopyToAsync() causes an exception on 2nd+ execution

### ISSUE THREAD

**Issue by rue-vmom** [aspnet/Mvc#7154]
I get the following exception after calling my controller on the 2nd and subsequence calls:
```
[HttpPut("{id}")]
public async void Put(string id, [FromForm]string data, [FromForm]List<IFormFile> media) {
     using (var memoryStream = new MemoryStream()) {
          await media[0].CopyToAsync(memoryStream);
     }
}
```

The first call to this controller action works, but the 2nd time will produce this exception until a restart:
```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Kernel32.SetFilePointerEx(SafeFileHandle hFile, Int64 liDistanceToMove, Int64& lpNewFilePointer, UInt32 dwMoveMethod)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.ReadNativeAsync(Byte[] bytes, Int32 offset, Int32 numBytes, Int32 numBufferedBytesRead, CancellationToken cancellationToken)
   at System.IO.FileStream.ReadAsyncInternal(Byte[] array, Int32 offset, Int32 numBytes, CancellationToken cancellationToken)
   at System.IO.FileStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.<ReadAsync>d__35.MoveNext()
```

Switching to use IFormFile.CopyTo() gets rid of the error, but it's no longer async.  Thanks!

**Comment by pranavkm** [comment]
You need to define the action as `async Task` not `async void`.

**Comment by rue-vmom** [comment]
Ahh yes, thank you!
