### ISSUE TITLE
Using a type from a .Net Standard Library with AssemblyCulture set throws FileNotFoundException

### ISSUE THREAD

**Issue by kyleherzog** [aspnet/Mvc#7197]
If I try to use a class from a .Net Standard library in a asp.net core project I get a FileNotFoundException referencing the .dll file of the .Net Standard library.  The error message displayed also references the following exception: "ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information." This error shows up on all pages on the site.   This only happens if an AssemblyCulture attribute is set on the .Net Standard library.

Steps to reproduce:
1.	Create a new ASP.net core site using the Web API template
2.	Add a .Net Standard project to the solution
3.	Add a project reference to the .Net Standard project to the asp.net core site.
4.	Add a blank class to the asp.net core site called ChildClass and have it inherit from Class1 in the .Net Standard project
5.	Add an AssemblyInfo.cs file to the .Net Standard project
6.	Remove assembly attributes in AssemblyInfo that are auto created by the .Net Standard project (AssemblyTitle, AssemblyConfiguration, AssemblyCompany, AssemblyProduct, AssemblyVersion, AssemblyFileVersion)
7.	Set the AsseblyCulture to “en-US”

**Comment by pranavkm** [comment]
Could you include the stack trace for the exception?

**Comment by kyleherzog** [comment]
Here is the stack trace info...
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by pranavkm** [comment]
@kyleherzog the docs for [`AssemblyCulture`](https://msdn.microsoft.com/en-us/library/system.reflection.assemblycultureattribute(v=vs.110).aspx#Anchor_6) says that the attribute is only meant to mark satellite assemblies. Satellite assemblies cannot contain code, only culture specific resources. Why do you set a value for the attribute?

**Comment by kyleherzog** [comment]
I don't need the value, and my fix for the situation is to just remove it.  I've historically set the attribute just because it is a part of the default AssemblyInfo.cs template.  However, it doesn't seem like it should break the entire site by being there.  I can use the .Net Standard library with the AssemblyCulture set in a Xamarin project without issue.

**Comment by mkArtakMSFT** [comment]
@kyleherzog, this is by design, according to the documentation @pranavkm had referenced. It looks like it's not correct for Xamarin apps either.
