### ISSUE TITLE
Error deploy site in server

### ISSUE THREAD

**Issue by KIBASSA** [aspnet/Mvc#7311]
Hi everyone,
I obtains this error after deploy site on server when I didn't change anything in the file startup. cs

`System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.MvcViewFeaturesMvcCoreBuilderExtensions.AddViews(IMvcCoreBuilder builder)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Emiko.Site.Client.Startup.ConfigureServices(IServiceCollection services) in C:\Users\User\source\repos\CineBot\Emiko.Site.Client\Startup.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
`

Anybody have any idea how I can solve this problem?

Thanks,

**Comment by KIBASSA** [comment]
Everything is ok after upgrade donet sdk on server :)
