### ISSUE TITLE
View compilation fails from .NET Standard 2.0 library

### ISSUE THREAD

**Issue by cerebrate** [aspnet/Mvc#7338]
Background: I have a project made up of multiple "picoservices", each implemented inside a .NET Standard 2.0 class library, in turn all loaded and run by a .NET Framework application. One of these "picoservices" generates a web UI using the Kestrel web server and, in theory, MVC with embedded views.

However, when I attempt to access the resulting site, the views fail to compile due to being unable to find references, thus:

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\avatar\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Started web server.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:6000/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method TestMvcLib.Controllers.HomeController.Index (TestMvcLib) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action TestMvcLib.Controllers.HomeController.Index (TestMvcLib) in 3974.5576ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLBE8U6OOL4V", Request id "0HLBE8U6OOL4V:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
ccjhoulr.5ru(4,62): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(4,81): error CS0518: Predefined type 'System.String' is not defined or imported
ccjhoulr.5ru(4,110): error CS0518: Predefined type 'System.Type' is not defined or imported
ccjhoulr.5ru(4,11): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(8,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
ccjhoulr.5ru(9,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
ccjhoulr.5ru(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
ccjhoulr.5ru(11,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
ccjhoulr.5ru(14,36): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
ccjhoulr.5ru(15,94): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
ccjhoulr.5ru(15,94): error CS0518: Predefined type 'System.Boolean' is not defined or imported
ccjhoulr.5ru(15,45): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(18,67): error CS1983: The return type of an async method must be void, Task or Task<T>
ccjhoulr.5ru(18,39): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
ccjhoulr.5ru(32,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
ccjhoulr.5ru(32,118): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(34,49): error CS0234: The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
ccjhoulr.5ru(34,71): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(36,49): error CS0234: The type or namespace name 'IViewComponentHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
ccjhoulr.5ru(36,87): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(38,59): error CS0234: The type or namespace name 'IJsonHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
ccjhoulr.5ru(38,83): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(40,59): error CS0234: The type or namespace name 'IHtmlHelper<>' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
ccjhoulr.5ru(40,71): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(40,71): error CS0518: Predefined type 'System.Object' is not defined or imported
ccjhoulr.5ru(40,71): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
ccjhoulr.5ru(40,71): error CS0518: Predefined type 'System.Boolean' is not defined or imported
ccjhoulr.5ru(40,92): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(18,67): error CS0508: '_Views_Home_Index_cshtml.ExecuteAsync()': return type must be 'Task' to match overridden member 'RazorPageBase.ExecuteAsync()'
ccjhoulr.5ru(18,67): error CS0012: The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(31,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(31,10): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(33,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(33,10): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(35,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(35,10): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(37,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(37,10): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(39,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(39,10): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(26,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(26,13): error CS0518: Predefined type 'System.Object' is not defined or imported
ccjhoulr.5ru(26,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
ccjhoulr.5ru(26,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
ccjhoulr.5ru(26,34): error CS0518: Predefined type 'System.Boolean' is not defined or imported
ccjhoulr.5ru(26,13): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(27,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(27,13): error CS0518: Predefined type 'System.Object' is not defined or imported
ccjhoulr.5ru(27,26): error CS0518: Predefined type 'System.String' is not defined or imported
ccjhoulr.5ru(27,13): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(28,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
ccjhoulr.5ru(28,13): error CS0518: Predefined type 'System.Object' is not defined or imported
ccjhoulr.5ru(28,13): error CS0518: Predefined type 'System.Void' is not defined or imported
ccjhoulr.5ru(18,67): error CS0161: '_Views_Home_Index_cshtml.ExecuteAsync()': not all code paths return a value
ccjhoulr.5ru(15,18): error CS0518: Predefined type 'System.Void' is not defined or imported
/Views/Home/Index.cshtml(2,5): error CS0012: The type 'ViewDataDictionary<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
/Views/Home/Index.cshtml(2,14): error CS0518: Predefined type 'System.String' is not defined or imported
/Views/Home/Index.cshtml(2,25): error CS0518: Predefined type 'System.String' is not defined or imported
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 4347.8817ms 500
```

In lieu of attempting to figure out all the relevant details of the setup to mention, please find simple reproduction project enclosed:

[TestMvc.zip](https://github.com/aspnet/Mvc/files/1703963/TestMvc.zip)

If not a bug, any thoughts on making this work would be very much appreciated!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @cerebrate. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@rynowak do you have any thoughts here?

**Comment by rynowak** [comment]
Hi @cerebrate 

Both the projects that you included were created using older-style .csproj and don't include the Web SDK. This means that these project don't have the necessary support to tell the ASP.NET Core runtime what the compilation references are. I'd recommend using one of the tutorials here as a starting point. https://docs.microsoft.com/en-us/aspnet/core/tutorials/index

These will direct you to create projects using `dotnet new` at the command line, or the .NET Core project templates in Visual Studio

![image](https://user-images.githubusercontent.com/1430011/36050746-963f5eb0-0d9c-11e8-86cc-e4e87588700b.png)

**Comment by rynowak** [comment]
Closing this as it's not an issue. View compilation is not supported for older-style .csproj files.

**Comment by cerebrate** [comment]
@rynowak Thanks for your answer, and I apologize for bothering you again, but if you'd indulge a question or two on the greater-scope issue --

I've been looking at those tutorials again, and while I can create a project just fine using them, what I can't seem to do is host it inside another .NET Core application. I have rejiggered things as much as I can, but I can't seem to find a way to compile the web application project as a class library and start the web host from an app referencing it.

Unfortunately, this is essential to what I'm trying to implement, which is a hosted web UI for the application in question.

Is this even possible? And if it is, are there any tutorials that address this particular scenario?

Thanks muchly,

@cerebrate

**Comment by rynowak** [comment]
> I've been looking at those tutorials again, and while I can create a project just fine using them, what I can't seem to do is host it inside another .NET Core application. I have rejiggered things as much as I can, but I can't seem to find a way to compile the web application project as a class library and start the web host from an app referencing it.

We're working on making this kind of thing easy in 2.1. You'll be able to see working with the identity UI in 2.1.0-preview1 and it will be easy for you to do in preview2.
