### ISSUE TITLE
app.UseExceptionHandler Mvc on a mac crashes dotnet

### ISSUE THREAD

**Issue by CoderJason123** [aspnet/Mvc#7368]
Hello.  I have an mvc aspnet core 2.0 app and started testing exceptions.  I am throwing all sorts of exceptions to test, regular exception, unauthorized exception, and so on, and the global error handler does not work.

Dotnet crashes and the mvc app is no longer receiving requests.  I've placed
           app.UseExceptionHandler() before app.UseMvc().  No difference.  The only thing I see different about my setup than other articles is that I am using a mac os High Sierra.  The stack trace from my exception that I generate is...
Unhandled Exception: System.Exception: hey this is an exception
   at yyyyyService.<CheckAccountId>d__12.MoveNext() in /Users/jason/Documents/Service.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

I've fiddled with this for a few hours to no avail.  Yes, I have tried changing from dev to production but my code only invokes the production app.UseExceptionHandler() from the standard startup.cs class.

Any thoughts on where i can go from here?

**Comment by benaadams** [comment]
Are you using `async void` methods rather than `async Task` or queuing items directly to threadpool?

**Comment by CoderJason123** [comment]
All of my controller methods are like this..so async await all the way thru.  no voids.  it's like it skips the exception handler altogether.

  public async Task<HttpResponseMessage>

**Comment by davidfowl** [comment]
Doesn’t look like the exception is happening on a request thread.

**Comment by Eilon** [comment]
@CoderJason123 can you post your app to a GitHub repo so we can take a look?

**Comment by khellang** [comment]
`ThreadPoolWorkQueue.Dispatch()` looks suspicious. Unhandled exceptions on thread pool threads has always been problematic.

**Comment by davidfowl** [comment]
> Unhandled exceptions on thread pool threads has always been problematic.

They crash the process 😄

**Comment by khellang** [comment]
> Dotnet crashes and the mvc app is no longer receiving requests.

Exactly 😉

**Comment by CoderJason123** [comment]
everyone, if you take the dotnet new mvc app, and make everything async, that is what is I have, literally.  i have not created thread pools manually or anything else.  The stack trace gives me little to go on, as you can see.  Is this a problem because I'm using async controllers?

**Comment by davidfowl** [comment]
I don't think it has anything do with async controllers. I think there's code in your application that's either using async void or scheduling work on the thread pool and an exception is being thrown from it.

What is this file and what is on line 75?

> /Users/jason/Documents/Service.cs:line 75

**Comment by CoderJason123** [comment]
@davidfowl -- that is just my service.  My controller calls my service which does the work and business logic.  I really wish I could get on board with folks telling me I'm scheduling work on a thread pool or doing an async void, but I am not.  So, nothing directly.  But, I am willing to investigate something in the framework that is doing this under the covers.

**Comment by CoderJason123** [comment]
Guess what, you guys were right, i was wrong.  How's that for eating your own words?  The code that threw an exception was an async void because all i needed it to do was throw an exception if a data condition didn't exist.  I changed it to async task<bool> and all is well.
