### ISSUE TITLE
Assigning to the context's Result property, when implementing IPageFilter, causes an exception.

### ISSUE THREAD

**Issue by stevenbey** [aspnet/Mvc#7373]
Common logic, within an MVC Action or Razor Pages Handler, is to check, immediately, whether the ModelState is valid and, if not, return the View, Page or a Bad Request result (see Figure 1).

To eliminate this repeated code pattern, I have created an Action Filter that performs the check and, when appropriate, assigns a new `BadRequestObjectResult` to the context's `Result` property (See Figure 2).

I am trying to do something similar in my Razor Pages (See Figure 3) but this results in an exception being thrown.  _I suspect this would also happen if a new `ViewResult` was assigned to the `Result` property, in the Action Filter, although I haven't test this hypothesis._

[The documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.pagehandlerexecutingcontext?view=aspnetcore-2.0) explains that 'Setting Result to a non-null value inside a page filter will short-circuit the page and any remaining page filters.'; however, the code in Figure 3 is no different, logically, than the code in Figure 4 (calling `Page()` returns an 'empty' `PageResult`, which gets populated later in the pipeline) and so the execution of the Handler should be by-passed and the rest of the pipeline should use the Page Filter's PageResult object.  _Likewise, when setting a new `ViewResult` to the `Result` property, in the Action Filter_

Figure 1:

    [HttpPost]
    public async Task<IActionResult> Create(CreateModel model)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
    
        ...
    }

Figure 2:

    public void OnActionExecuting(ActionExecutingContext context) => context.Result = context.ModelState.IsValid ? null : new BadRequestObjectResult(context.ModelState);

Figure 3:

    public void OnPageHandlerExecuting(PageHandlerExecutingContext context) => context.Result = context.ModelState.IsValid ? null : new PageResult();

Figure 4:

    public Task<IActionResult> OnPostAsync([FromBody] CreateModel model)
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        ...
    }

### Minimal repro steps
Please see the [attached file](https://github.com/aspnet/Mvc/files/1725594/RazorPagesIssue.zip).

### Expected result
The page should be displayed.

### Actual result
An exception is thrown:

    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageResultExecutor.ExecuteAsync(PageContext pageContext, PageResult result)
       at Microsoft.AspNetCore.Mvc.RazorPages.PageResult.ExecuteResultAsync(ActionContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

### Further technical details
The exception is throw because the `Page` property, of the `PageResult`, is null.  It is possible to instantiate a Page but an exception is still thrown, due to the `ViewContext` property being null.  It is not possible to populate the `ViewContext` property, within the Page Filter.

**Comment by rynowak** [comment]
Based on the call stack, this looks like an actual functional bug. Thanks for the report!
