### ISSUE TITLE
Flaky test: HeaderBinder_BindsHeaders_ToSimpleTypes

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#7560]
This test fails occasionally:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinder.HeaderValueProvider.ContainsPrefix(String prefix) in C:\b\w\f9da89f9a35bf700\src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\Binders\HeaderModelBinder.cs:line 226
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinder`1.BindModelAsync(ModelBindingContext bindingContext) in C:\b\w\f9da89f9a35bf700\src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\Binders\CollectionModelBinder.cs:line 84
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinder.BindModelAsync(ModelBindingContext bindingContext) in C:\b\w\f9da89f9a35bf700\src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\Binders\HeaderModelBinder.cs:line 117
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderTests.HeaderBinder_BindsHeaders_ToSimpleTypes(String headerValue, Type modelType, Object expectedModel) in C:\b\w\f9da89f9a35bf700\test\Microsoft.AspNetCore.Mvc.Core.Test\ModelBinding\Binders\HeaderModelBinderTests.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
```

Future instances of this failure will appear [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:ModelBingingNullRef,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by pranavkm** [comment]
@kichalla should this be investigated for preview2?

**Comment by mkArtakMSFT** [comment]
@kichalla can you please handle this? Thanks!

**Comment by mkArtakMSFT** [comment]
@kichalla, please also assign a cost.

**Comment by kichalla** [comment]
cc @mkArtakMSFT @ryanbrandenburg
