### ISSUE TITLE
MVC.Testing incompatible with conventional routing in current MVC apps

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7617]
See also #7615. This issue appears unrelated though the scenarios are similar. In particular, this one is about conventional routing rather than redoing pre-compilation (and failing).
## Repro Steps
The following is similar to the [Preview 1 functional testing instructions](https://blogs.msdn.microsoft.com/webdev/2018/03/05/asp-net-core-2-1-0-preview1-functional-testing-of-mvc-applications/) but done In Visual Studio using Preview 2 bits:
1. Create new ASP.NET Core Web Application
    - Later steps make more sense if "Create directory for solution" is enabled
2. Choose Web Application (Model-View-Controller) i.e. an MVC app (not Razor) and your favourite authentication scheme
3. Hit F5 or Ctrl-F5 to confirm app works fine
4. Add an xUnit Test Project (.NET Core) to the solution
5. Edit test project file to bump up the target framework: `<TargetFramework>netcoreapp2.1</TargetFramework>`
    - current Microsoft.AspNetCore.App package used in web application project is not compatible with a lower TFM
6. Add a reference from the test project to the web application project
7. Use Manage NuGet Packages to add a Microsoft.AspNetCore.Mvc.Testing package dependency to the test project
    - choose same version e.g. `2.1.0-preview2-30552` as Microsoft.AspNetCore.App package in the web application project
8. Edit UnitTest1 to perform a simple test:
    ``` c#
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc.Testing;
    using RazorApp1;
    using Xunit;

    namespace FunctionalTest
    {
        public class UnitTest1 : IClassFixture<WebApplicationFactory<Startup>>
        {
            private readonly HttpClient _client;

            public UnitTest1(WebApplicationFactory<Startup> factory)
            {
                _client = factory.CreateDefaultClient();
            }

            [Fact]
            public async Task Test1()
            {
                // Arrange & Act
                var response = await _client.GetAsync("https://localhost/");

                // Assert
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            }
        }
    }
    ```
    - use "http://localhost" if you chose _not_ to include HTTPS support when creating the web application project
9. Use Test Explorer to Run All tests

### Expected
The one test succeeds.
### Actual
Test fails because the site returns a 404 status code.

## Versions
Microsoft Visual Studio Enterprise 2017: `15.7.0 Preview 3.0 [27604.0.d15.7]`
.NET Core SDK: `2.1.300-preview2-008523`
Microsoft.NETCore.App: `2.1.0-preview2-26403-06`
Microsoft.AspNetCore.App: `2.1.0-preview2-30552`
Microsoft.AspNetCore.Mvc.Testing: `2.1.0-preview2-30552`

**Comment by dougbu** [comment]
Similar scenario using .NET Framework 4.6.1 succeeds. Major differences in successful case are the TFM and use of .NET Framework-compatible packages (not Microsoft.AspNetCore.App).

**Comment by dougbu** [comment]
Found while verifying aspnet/Release#257.

**Comment by dougbu** [comment]
Expected an attribute routing scenario to get much further or even succeed. But, above setup also fails when action has `[HttpGet("/api/test")]` for example.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this? Thanks!

**Comment by javiercn** [comment]
I suspect this is related to the application part changes. @pranavkm

**Comment by pranavkm** [comment]
Investigated this further. In 2.1.0-preview1, this worked because we always returned a part for the EntryAssembly regardless of if it depended on Mvc:

https://github.com/aspnet/Mvc/blob/2.1.0-preview1-final/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultAssemblyPartDiscoveryProvider.cs#L78

The problem resurfaces if the web application under test references a class library which references Mvc. Essentially any reference to the shared runtime or one of it's dependencies gets erased and is unreliable. It's super weird how it works. Maybe this is yet form of https://github.com/dotnet/sdk/issues/2092.

Anyway, the fix here which seems like the right thing to do is to use `CompileLibraries` rather than `RuntimeLibraries` to determine if a library depends on Mvc. It also allows us to remove this - https://github.com/aspnet/Mvc/commit/5e019bd707497b0d28a7387c7ed66447a1907d59 - since querying the compile libraries correctly states that `Microsoft.AspNetCore.All` depends on `Microsoft.AspNetCore.Mvc`.

cc @eerhardt to get his thoughts on this.

cc @JunTaoLuo for the `Microsoft.AspNetCore.All` stuff

**Comment by pranavkm** [comment]
Filed https://github.com/aspnet/Mvc/issues/7632 to track verifying this E2E once we have a shared runtime

**Comment by tbertenshaw** [comment]
Is there a workaround to this whilst awaiting the next release?

**Comment by dougbu** [comment]
@tbertenshaw @pranavkm fixed this in the next release. In the meantime, you can change affected projects to reference individual packages e.g. 
``` xml
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.0-preview2-final" />
<PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.1.0-preview2-final" />
<PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.0-preview2-final"/>
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-preview2-final" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.1.0-preview2-final" PrivateAssets="All" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0-preview2-final" />
```
instead of a shared runtime
``` xml
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview2-final" />
```

**Comment by tbertenshaw** [comment]
Still get razor errors, do I need to reference all in the test and the web projects?

**Comment by javiercn** [comment]
@tbertenshaw Can you post the errors here? That way we can identify what references might be missing

**Comment by tbertenshaw** [comment]
```
Test Name:	Timbo.Spike.Web.Functional.Tests.AnonUserHomePageActions.CanGetAboutPage
Test FullName:	Timbo.Spike.Web.Functional.Tests.AnonUserHomePageActions.CanGetAboutPage
Test Source:	C:\dev\github\Timbo\Timbo.Core\src\Tests\Timbo.Spike.Web.Functional.Tests\AnonUserHomePageActions.cs : line 37
Test Outcome:	Failed
Test Duration:	0:00:03.865

Result StackTrace:	
at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Timbo.Spike.Web.Functional.Tests.AnonUserHomePageActions.CanGetAboutPage() in C:\dev\github\Timbo\Timbo.Core\src\Tests\Timbo.Spike.Web.Functional.Tests\AnonUserHomePageActions.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
Result Message:	
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException : One or more compilation failures occurred:
boyllm3c.oka(4,41): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
boyllm3c.oka(5,44): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
boyllm3c.oka(4,122): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(4,145): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(5,89): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(5,113): error CS0518: Predefined type 'System.Type' is not defined or imported
boyllm3c.oka(9,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(11,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(12,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(15,36): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(31,35): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
boyllm3c.oka(32,35): error CS0234: The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
boyllm3c.oka(31,78): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(31,87): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(31,132): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(32,78): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(32,87): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(32,132): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(33,65): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(36,67): error CS1983: The return type of an async method must be void, Task or Task<T>
boyllm3c.oka(36,39): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
boyllm3c.oka(70,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(70,118): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(72,49): error CS0234: The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(72,71): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(74,49): error CS0234: The type or namespace name 'IViewComponentHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(74,87): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(76,59): error CS0234: The type or namespace name 'IJsonHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
boyllm3c.oka(76,83): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(78,59): error CS0234: The type or namespace name 'IHtmlHelper<>' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
boyllm3c.oka(78,71): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(78,71): error CS0246: The type or namespace name 'AboutModel' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(78,95): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(79,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(79,81): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(79,81): error CS0246: The type or namespace name 'AboutModel' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(80,16): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(80,16): error CS0246: The type or namespace name 'AboutModel' could not be found (are you missing a using directive or an assembly reference?)
boyllm3c.oka(36,67): error CS0115: 'Pages_About.ExecuteAsync()': no suitable method found to override
boyllm3c.oka(69,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
boyllm3c.oka(69,10): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(71,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
boyllm3c.oka(71,10): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(73,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
boyllm3c.oka(73,10): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(75,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
boyllm3c.oka(75,10): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(77,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
boyllm3c.oka(77,10): error CS0518: Predefined type 'System.Void' is not defined or imported
boyllm3c.oka(44,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(44,13): error CS0103: The name 'BeginContext' does not exist in the current context
boyllm3c.oka(44,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(44,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(44,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
boyllm3c.oka(45,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(45,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
boyllm3c.oka(45,26): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(46,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(46,13): error CS0103: The name 'EndContext' does not exist in the current context
boyllm3c.oka(47,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(47,13): error CS0103: The name 'BeginContext' does not exist in the current context
boyllm3c.oka(47,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(47,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(47,34): error CS0518: Predefined type 'System.Boolean' is not defined or imported
boyllm3c.oka(53,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(53,13): error CS0103: The name 'EndContext' does not exist in the current context
boyllm3c.oka(54,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(54,13): error CS0103: The name 'BeginContext' does not exist in the current context
boyllm3c.oka(54,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(54,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(54,34): error CS0518: Predefined type 'System.Boolean' is not defined or imported
boyllm3c.oka(55,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(55,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
boyllm3c.oka(55,26): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(56,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(56,13): error CS0103: The name 'EndContext' does not exist in the current context
boyllm3c.oka(57,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(57,13): error CS0103: The name 'BeginContext' does not exist in the current context
boyllm3c.oka(57,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(57,31): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(57,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
boyllm3c.oka(63,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(63,13): error CS0103: The name 'EndContext' does not exist in the current context
boyllm3c.oka(64,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(64,13): error CS0103: The name 'BeginContext' does not exist in the current context
boyllm3c.oka(64,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(64,31): error CS0518: Predefined type 'System.Int32' is not defined or imported
boyllm3c.oka(64,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
boyllm3c.oka(65,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(65,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
boyllm3c.oka(65,26): error CS0518: Predefined type 'System.String' is not defined or imported
boyllm3c.oka(66,13): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(66,13): error CS0103: The name 'EndContext' does not exist in the current context
boyllm3c.oka(36,67): error CS0161: 'Pages_About.ExecuteAsync()': not all code paths return a value
boyllm3c.oka(79,183): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(79,183): error CS0103: The name 'PageContext' does not exist in the current context
boyllm3c.oka(79,139): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
boyllm3c.oka(79,171): error CS0518: Predefined type 'System.Object' is not defined or imported
boyllm3c.oka(79,171): error CS0246: The type or namespace name 'AboutModel' could not be found (are you missing a using directive or an assembly reference?)
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\_ViewImports.cshtml(1,28): error CS0234: The type or namespace name 'Identity' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\_ViewImports.cshtml(3,20): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'Timbo.Spike' (are you missing an assembly reference?)
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(4,14): error CS0518: Predefined type 'System.String' is not defined or imported
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(4,25): error CS0518: Predefined type 'System.String' is not defined or imported
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(6,1): error CS0518: Predefined type 'System.Object' is not defined or imported
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(6,1): error CS0103: The name 'Write' does not exist in the current context
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(6,16): error CS0518: Predefined type 'System.String' is not defined or imported
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(7,1): error CS0518: Predefined type 'System.Object' is not defined or imported
C:\dev\github\Timbo\Timbo.Core\src\_web\Timbo.Spike.Web\Pages\About.cshtml(7,1): error CS0103: The name 'Write' does not exist in the current context

```
@javiercn

**Comment by javiercn** [comment]
@tbertenshaw That sounds like a Razor compilation error.

* Have you disabled compilation on build?
* Have you disabled shadowcopying assemblies?
  * See instructions on how to do it in xUnit https://xunit.github.io/docs/configuring-with-json.html
* Can you validate that there is a Timbo.Spike.Web.deps.json file on the test output folder?

**Comment by guardrex** [comment]
Side note ... same thing here working with the sample app for the upcoming integration testing topic, but your workaround @dougbu worked :+1: :smile: ...

```xml
<ItemGroup>
  <!--<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview2-final" />-->
  <PackageReference Include="Microsoft.AspNetCore" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.0-preview2-final"/>
  <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.1.0-preview2-final" PrivateAssets="All" />
  <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.0-preview2-final" />
  <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="2.1.0-preview2-final" />
</ItemGroup>
```

**Comment by tbertenshaw** [comment]
Managed to fix it by adding 
`    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />`
to my FunctionalTests csproj.

Seems obvious but didn't spot updated docs so wasn't sure what steps were needed.

**Comment by guardrex** [comment]
@tbertenshaw Docs are in the works :point_right: https://github.com/aspnet/Docs/pull/6086

Fairly early stages tho ... engineering hasn't looked at the PR yet ... so keep that in mind if you read/follow any advice provided.

**Comment by JunTaoLuo** [comment]
FYI the workaround was discussed in #7710
