### ISSUE TITLE
ASP.NET Core 2.1 Preview 2 - AddMvcCore() throws ArgumentNullException when hosting model is InProcess

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/Mvc#7633]
When using AddMvcCore() and hosting model is InProcess, the following exception is thrown when starting the site.

```

System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError, Func`2 fileExists, Func`2 loadFile)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetRelatedAssemblies(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetAssemblyItem(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveFromDependencyContext(DependencyContext dependencyContext)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveAssemblies(Assembly entryAssembly)+MoveNext()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at WebApplication1.Startup.ConfigureServices(IServiceCollection services) in D:\Dev2017\WebApplication1\WebApplication1\Startup.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

```
Dev Machine Setup:
Visual Studio 2017 15.7 Preview 3
dotnet-sdk-2.1.300-preview2-008530-win-x64

Steps to reproduce:

1) Create default MVC 2.1 Preview 2 application.
2) Replace

   `services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
`
with

```

   services.AddMvcCore()
           .AddAuthorization()
           .AddRazorViewEngine()
           .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);


``` 
in Startup.cs.
3) Add `<AspNetCoreModuleHostingModel>InProcess</AspNetCoreModuleHostingModel>` to csproj.
4) Start the site.

**Comment by pranavkm** [comment]
Seems like a dup of https://github.com/aspnet/IISIntegration/issues/725. @jkotalik ?

**Comment by jkotalik** [comment]
Yeah.

**Comment by g136660** [comment]
> 3) Add <AspNetCoreModuleHostingModel>InProcess</AspNetCoreModuleHostingModel> to csproj.

What section i must use for this tag?
