### ISSUE TITLE
Is it possible to do web api attribute routing by content type?

### ISSUE THREAD

**Issue by plutext** [aspnet/Mvc#7755]
#### Is this a Bug or Feature request?:
feature request

#### Description of the problem:

I'd like to be able to consume either posted JSON or form data at the same endpoint.

https://andrewlock.net/model-binding-json-posts-in-asp-net-core/ suggests using different endpoints, but I can't do that on this occasion

https://massivescale.com/web-api-routing-by-content-type/ suggests a way to do it for asp.net; is something like this available in core mvc?

 in Java's JAX-RS for example, there is @Consumes

**Comment by rynowak** [comment]
We have a similar feature - I looked and it unfortunately isn't covered in the docs. 

It would look like:
```
[HttpPost("api/test/bytype")]
[Consumes("application/json")]
public void ActionForJson()
{
...
}

[HttpPost("api/test/bytype")]
[Consumes("application/x-www-form-urlencoded"")]
public void ActionForJson()
{
...
}
```

**Comment by plutext** [comment]
Thanks a lot for the quick response!  Trying it now, it doesn't seem to play nice with CORS handling.

For example, client sends:

```
OPTIONS /editService/createSession HTTP/1.1
Host: localhost:5000
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:9001
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

```
Having implemented CORS handling using the usual services.AddCors, the OPTIONS request causes: ```
Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied
  at Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestCandidate(RouteContext context, IReadOnlyList`1 candidates)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.RouteAsync(RouteContext context)

```
And I can't seem to work around that by adding something like:

```
        [HttpOptions("createSession")]
        [Consumes("application/json")]
        public void CreateSessionJsonOptions() {

        }
        [HttpOptions("createSession")]
        [Consumes("application/x-www-form-urlencoded")]
        public void CreateSessionFormOptions() {

        }

```
With that, I still get the same error

**Comment by rynowak** [comment]
Are you trying to handle CORS requests yourself? It's not very typical to handle options requests manually.

Can you describe how you have CORS configured? Do you have one policy you want to apply globally? or are you trying to apply different behaviors per action?

**Comment by rynowak** [comment]
The doc here discusses CORS in ASP.NET Core. https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1

Note that generally you'd either want to use the middleware **or** the attributes.

**Comment by plutext** [comment]
For cors, I have the following attribute on my controller class:

` [EnableCors("AllowAllOrigins")]`

and in Startup.cs I have:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAllOrigins",
                    builder => builder.AllowAnyOrigin()
                                        .AllowAnyMethod()
                                        .AllowAnyHeader()
                                        .AllowCredentials()); 
            }); 
            services.AddMvc();

```
This was working fine when I had just a single endpoint method (ie either for JSON or form binding, not both).

I don't want to handle options requests manually;  what I posted a few hours ago was just an attempt to get around the AmbiguousActionException which the OPTIONS request is causing.

**Comment by rynowak** [comment]
OK, could you post what your actual action signatures look like so we can investigate this?

In the mean time I expect that adding something like the below will work around your problem:
```
        [HttpPost("createSession")]
        public void CORSHACK() {
             return StatusCode(415);
        }

        [HttpPost("createSession")]
        [Consumes("application/json")]
        public void CreateSessionJsonOptions() {

        }
        [HttpPost("createSession")]
        [Consumes("application/x-www-form-urlencoded")]
        public void CreateSessionFormOptions() {

        }
```

The extra action method will be an additional candidate for action selection, but won't get run in CORS cases. Then if someone does manage to reach it, they will get a 415.

**Comment by plutext** [comment]
CORSHACK() (returning StatusCodeResult) worked fine thanks.

My actual signatures are:

```
        [HttpPost("createSession")]
        [Consumes("application/json")]
        public async Task<IActionResult> CreateSessionPostedJson([FromBody] CreateSessionData data)   

        [HttpPost("createSession")]
        [Consumes("application/x-www-form-urlencoded")]
        public async Task<IActionResult> CreateSessionPostedForm(    		
            [FromForm(Name = "param1")] String param1,
/* 6 similar args omitted */
            [FromForm(Name = "param8")] String param8)

```
CreateSessionData is just a bunch of string fields with getters/setters.

**Comment by rynowak** [comment]
@mkArtakMSFT  - this is worth having someone investigate. It looks like using `[Consumes]` and CORS together doesn't work without a spooky workaround.

**Comment by mkArtakMSFT** [comment]
Thanks @rynowak.

@javiercn, can you please look into this?
