### ISSUE TITLE
WebApplicationFactory<T> not calling appropriate ConfigureServices

### ISSUE THREAD

**Issue by mhagrelius** [aspnet/Mvc#7785]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

1. Create an a web application project, add a ConfigureServicesDevelopment function and add a service to the ServiceCollection
2. Create an xunit project and follow the guide from today's Asp.Net Community Standup for utilizing the new WebApplicationFactory from Microsoft.AspNetCore.Mvc.Testing 

#### Description of the problem:
I have a project that depends on Hangfire. I have been experimenting with splitting my ConfigureServices into Development vs Production by following the Asp.Net Core Docs. During normal run of the program ConfigureServicesDevelopment(IServiceCollection services) is called and my             services.AddHangfire(h => h.UseMemoryStorage()); is called and setup.

However, when running a basic xunit test I receive an exception (pasted below). If I move the calls into the normal ConfigureServices method, my tests pass.

`public RoutesTests(WebApplicationFactory<Program> fixture)
        {
            Client = fixture.CreateClient();
        }

        public HttpClient Client { get; }

        [Theory]
        [InlineData("/api/phones")]
        public async Task AuthenticationRequired(string url)
        {
            var response = await Client.GetAsync(url);
            response.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
        }`

Test Name:	<omitted>Test.RoutesTests.AuthenticationRequired(url: "/api/phones")
Test FullName:	<omitted>.Test.RoutesTests.AuthenticationRequired
Test Source:	<omitted>RoutesTests.cs : line 22
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at Hangfire.HangfireApplicationBuilderExtensions.ThrowIfNotConfigured(IApplicationBuilder app)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireDashboard(IApplicationBuilder app, String pathMatch, DashboardOptions options, JobStorage storage)
   at <omitted>.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateServer(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at <omitted>.Test.RoutesTests..ctor(WebApplicationFactory`1 fixture)
Result Message:	System.InvalidOperationException : Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddHangfire' inside the call to 'ConfigureServices(...)' in the application startup code.

#### Version of ``Microsoft.AspNetCore.All`:
2.1.0-rc1-final

**Comment by khellang** [comment]
I thought this should've been fixed for RC1? https://github.com/aspnet/Mvc/commit/e0b4c13895fee575544f963b7dbc59d12f8ef7b4

**Comment by mhagrelius** [comment]
Yeah I saw that line in the source and wondered, but still doesn't appear to work for me.

**Comment by khellang** [comment]
I thought it was supposed to be `ConfigureDevelopmentServices` and `ConfigureProductionServices`?

https://github.com/aspnet/Hosting/blob/2575ebfcfe3f7019bd157fdbab8daaa1d8c45fdb/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L284-L285

**Comment by mhagrelius** [comment]
@khellang pointed out that I had named my methods incorrectly. Closing as the error was between keyboard and chair.
