### ISSUE TITLE
Error with Task<XElement> action return type

### ISSUE THREAD

**Issue by proggmatic** [aspnet/Mvc#7892]
#### Is this a Bug or Feature request?:
Bug (possible)

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

Request with header Accept: text/xml,application/xml

Startup.cs:
```csharp
services.AddMvc(options =>
{
    //options.RespectBrowserAcceptHeader = true;      // no matter if uncommented
    options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
    options.InputFormatters.Add(new XmlSerializerInputFormatter(options));
})

// No error
public XElement List()
{
    return new XElement("result", new XElement("item", new XAttribute("title", "blah")));
}

// Error: Unable to cast object of type 'System.Xml.Linq.XElement' to type 'System.Threading.Tasks.Task`1[System.Xml.Linq.XElement]'
public async Task<XElement> List()
{
    await Task.Delay(500);      // some async actions
    return new XElement("result", new XElement("item", new XAttribute("title", "blah")));
}
```

#### Description of the problem:
Error when i send request to action method with return type Task&lt;XElement&gt;.
Interesting that if i use Accept text/xml,application/xml, error is happens. But with Accept application/json everything is good.

Message: There was an error generating the XML document.
StackTrace:
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.Serialize(XmlSerializer xmlSerializer, XmlWriter xmlWriter, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context))

#### Version of `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @proggmatic.
This is due to a known issue, which is tracked here: https://github.com/aspnet/Mvc/issues/7782
We plan to include the fix in the upcoming patch release.
In the meantime, you can workaround the problem by changing the signature of the `List` method to return `ActionResult<T>` as follows:
```csharp
public async Task<ActionResult<XElement>> List()
```
