### ISSUE TITLE
Error message from Razor when compilation references are missing isn't meaningful

### ISSUE THREAD

**Issue by MrSmoke** [aspnet/Mvc#7910]
#### Is this a Bug or Feature request?: 
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Git repo: https://github.com/MrSmoke/RZ3007

- Publish WebApplication2 using `dotnet publish -c release -r win10-x64`
- Visit http://localhost:5000/

#### Description of the problem:
I'm getting the exception `Error RZ3007: Targeted tag name cannot be null or whitespace.` thrown when trying to use controllers and embedded views in a separate project to the startup project. 

The attached example project is essentially the New Project solution with the controller and view moved to a separate `ClassLibrary1` project and the views set to embedded resources. The views are fairly simple with no tag helpers being used all at.

It seems to work fine when debugging and only occurs when publishing the project.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

Stack trace
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
(0,0): Error RZ3007: Targeted tag name cannot be null or whitespace.
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MrSmoke.
@pranavkm, can you please look into this?

**Comment by MrSmoke** [comment]
I should also add that this was working in 2.0

**Comment by pranavkm** [comment]
@MrSmoke sent you a PR with suggested code changes for 2.1.

* We recommend using [RazorSdk](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio) and compiling views at build time rather than embedding them and having it compile at runtime. It takes away a lot of problem sources with missing reference assemblies (the cause of the issue here)
* If you do want to continue using embedded views, set `<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>` in your main app to continue publishing reference assemblies. https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1#properties has some more details about this.

**Comment by pranavkm** [comment]
Fixed the error message via:
* https://github.com/aspnet/Razor/commit/dbf13d65383ead3681ac56adf97bfadccf9a4bf4
* https://github.com/aspnet/Mvc/commit/a712ccc98ae84d208bd5f0817ed8e6320ca163c6

**Comment by sbabaei** [comment]
I have same problem but my views saved in  database and loading using virtual file provider . 
What can I do ? 
The project is work for me in debug and visual studio but when I publish and run outside IDE I see the problem : 
Targeted tag name cannot be null or whitespace.

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
