### ISSUE TITLE
Broken test: RazorViewEngine_RendersViewsFromEmbeddedFileProvider_WhenLookedupByPath

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#7922]
This test [fails](http://aspnetci/viewLog.html?buildId=487270&buildTypeId=XPlat_HighSierraOsxUniverse) 100% of the time on OSX with the following error:
```
System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Mvc.FunctionalTests.ViewEngineTests.RazorViewEngine_RendersIndexViewsFromEmbeddedFileProvider(String requestPath) in /_/test/Microsoft.AspNetCore.Mvc.FunctionalTests/ViewEngineTests.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please fix this? Thanks!

**Comment by ajaybhargavb** [comment]
3d32b6da2fb82c58984c495970e6325b2f5f1972
