### ISSUE TITLE
Views publishing compilation fails after upgrading to 2.1.1 because looks for views in wrong place (in obj folder)

### ISSUE THREAD

**Issue by guylando** [aspnet/Mvc#8027]
Executing:
`dotnet publish -f net461 -c Release -r win7-x64 -o bin\Release\PublishOutput`
worked fine before upgrading to dotnet 2.1.1.

Now it throws exception:
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code 1. [C:\Users\user\Desktop\project\project.csproj]

And in the exception it says it can't find the views and it looks for them in the wrong path.

Could not find a part of the path 'C:\Users\user\Desktop\project\obj\Release\net461\win7-x64\Razor\Views\AAA\VVV\CCC\VIEW.cshtml.cs'.
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
     at System.IO.StreamWriter..ctor(String path)
     at System.IO.File.WriteAllText(String path, String contents)
     at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.ExecuteCore(RazorConfiguration configuration, String projectDirectory, String tagHelperManifest, List`1 sources, List`1 outputs, List`1 relativePaths)
     at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.ExecuteCoreAsync()
     at Microsoft.AspNetCore.Razor.Tools.CommandBase.ExecuteAsync()

Why does it look for the view to compile in the obj folder?
How do I specify where are the views location in version 2.1.1? In version 2.1.0 they were found fine.

**Comment by pranavkm** [comment]
Do you have a repro app for this? I wasn't able to reproduce this using a project from the template. That said, the path that it's trying to write to is for the code-generated file and not the location of the view on disk.

**Comment by guylando** [comment]
Started creating an app to reproduce and didn't manage to reproduce and then I ran again the same publish script without changing anything and it worked. I guess its some concurrency bug or some cache problem (thus also hard to reproduce other than the exception logs I copied) but my problem was solved so I close this.
Thanks
