### ISSUE TITLE
InvalidOperationException when returning ModelState in XML format

### ISSUE THREAD

**Issue by benjcallaghan** [aspnet/Mvc#8055]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/benjcallaghan/TestModelErrors

#### Description of the problem:
I have a Web API controller with an action that takes a large collection of items through the request body. I have automatic 400 responses enabled, which returns the ModelState as the body of the HTTP 400 response. If the number of errors is less than the maximum number allowed, both JSON and XML formatting returns the collection of error messages. If the maximum number of errors has been exceeded, only JSON formatting works. The resulting JSON object has the following property in addition to the regular error messages: `"":["The input was not valid."]`. Attempting to return an XML response produces the following server-side exception:

```
System.InvalidOperationException: There was an error generating the XML document. ---> System.ArgumentException: The empty string '' is not a valid local name.
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at System.Xml.XmlWriter.WriteStartElement(String localName)
   at Microsoft.AspNetCore.Mvc.Formatters.Xml.SerializableErrorWrapper.WriteXml(XmlWriter writer)
   at System.Xml.Serialization.XmlSerializationWriter.WriteSerializable(IXmlSerializable serializable, String name, String ns, Boolean isNullable, Boolean wrapped)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSerializableErrorWrapper.Write1_Error(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.Serialize(XmlSerializer xmlSerializer, XmlWriter xmlWriter, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

The HttpClient calling this method then throws this exception:

```
Unhandled Exception: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at TestClient.Program.RunTest(String uri, TransactionCollection transactions) in C:\Users\bcallaghan\Documents\Projects\TestModelErrors\TestClient\Program.cs:line 28
   at TestClient.Program.Main(String[] args) in C:\Users\bcallaghan\Documents\Projects\TestModelErrors\TestClient\Program.cs:line 23
   at TestClient.Program.<Main>(String[] args)
```

The culprit seems to be the extra property visible in the JSON object. The empty key is valid in JSON, but not in XML. The message attached to that key doesn't hold much value since the full list of validation errors follows it. I've been advised that this may also occur when serializing any `IDictionary<string, object>` that contains the empty string as a key.

XML serialization is performed through `AddXmlSerializerFormatters()` in Startup.cs and is requested through the HTTP `Accept: application/xml` header.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.App 2.1.1

**Comment by dougbu** [comment]
@benjcallaghan looking a bit at the code, I suspect the problem is here: https://github.com/aspnet/Mvc/blob/a6987cc1cde88663e16430db9b4ebc1372b2c4f9/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/SerializableErrorWrapper.cs#L82-L84

That attempts to create an element named after a key from the dictionary. (The class is elided from your stack trace because you're using Release bits.)

If I'm correct, using `AddXmlDataContractSerializerFormatters(...)` unfortunately won't help. Sticking with JSON is probably the best workaround.

**Comment by dougbu** [comment]
@mkArtakMSFT should I fix this in 2.1.0 Preview 1 and what is the issue's priority?

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu. Please assign cost also.

**Comment by dougbu** [comment]
498fa2d72f
