### ISSUE TITLE
Flaky test: EndpointConstraint_Accept_ForNoRequestType_SelectsTheCandidateWithoutConstraintIfPresent

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#8139]
This test [fails](http://aspnetci/viewLog.html?buildId=514461&buildTypeId=Releases_22xPublic_OsxUniverse) occasionally with the following error:
```
System.NotSupportedException : Specified method is not supported.
   at Microsoft.AspNetCore.Routing.EndpointConstraints.EndpointSelectorCandidate..ctor(Endpoint endpoint, IReadOnlyList`1 constraints)
   at Microsoft.AspNetCore.Mvc.ConsumesAttributeTests.EndpointConstraint_Accept_ForNoRequestType_SelectsTheCandidateWithoutConstraintIfPresent(String contentType) in /_/test/Microsoft.AspNetCore.Mvc.Core.Test/ConsumesAttributeTests.cs:line 407
```

**Comment by ryanbrandenburg** [comment]
EndpointConstraint_Accept_ForNoMatchingCandidates_SelectsTheFirstCandidate [failed again](http://aspnetci/viewLog.html?buildId=514461&buildTypeId=Releases_22xPublic_OsxUniverse).

**Comment by ryanbrandenburg** [comment]
EndpointConstraint_Accept_UnrecognizedMediaType_SelectsTheCandidateWithoutConstraintIfPresent [failed again](http://aspnetci/viewLog.html?buildId=514459&buildTypeId=Releases_22xPublic_UbuntuUniverse).

**Comment by rynowak** [comment]
This was a build break introduced last night and fixed within an hour or two
