### ISSUE TITLE
some cshtml template pages are dynamically loaded.

### ISSUE THREAD

**Issue by qibunext** [aspnet/Mvc#8167]
```c#
<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
```

some cshtml template pages are dynamically loaded.
So the error occurred.

```c#
     <TargetFramework>netcoreapp2.1</TargetFramework>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <LangVersion>latest</LangVersion>
```

```c#
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
pxwuwnt0.vjr(5,62): error CS0433: The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(58,85): error CS0433: The type 'RazorPage<TModel>' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(61,67): error CS0115: 'wwwroot_Data_Common__Page.ExecuteAsync()': no suitable method found to override
pxwuwnt0.vjr(314,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(316,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(318,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(320,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(322,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(324,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(326,58): error CS0433: The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
pxwuwnt0.vjr(69,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(70,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(77,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(82,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(83,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(89,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(90,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(91,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(92,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(93,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(99,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(100,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(101,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(102,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(109,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(110,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(111,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(112,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(118,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(119,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(120,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(121,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(129,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(130,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(131,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(137,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(138,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(139,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(146,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(147,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(148,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(149,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(155,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(156,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(157,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(158,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(164,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(165,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(166,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(176,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(177,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(178,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(179,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(185,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(186,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(187,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(188,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(196,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(197,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(198,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(199,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(205,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(206,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(207,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(208,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(209,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(215,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(216,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(217,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(218,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(226,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(227,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(228,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(238,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(239,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(240,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(241,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(247,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(248,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(249,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(250,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(251,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(257,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(258,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(259,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(260,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(267,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(268,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(269,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(276,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(277,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(278,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(279,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(285,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context
pxwuwnt0.vjr(286,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(287,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(288,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(296,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(297,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(298,13): error CS0103: The name 'EndContext' does not exist in the current context
pxwuwnt0.vjr(304,13): error CS0103: The name 'BeginContext' does not exist in the current context
pxwuwnt0.vjr(305,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
pxwuwnt0.vjr(306,13): error CS0103: The name 'EndContext' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(2,12): error CS0117: 'Model' does not contain a definition for 'TotalCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(2,36): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(14,1): error CS0103: The name 'WriteAttributeValue' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(14,37): error CS0117: 'Model' does not contain a definition for 'PagerId'
/root/office/wwwroot/Data/Common/_Page.cshtml(15,27): error CS0103: The name 'Write' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(15,64): error CS0117: 'Model' does not contain a definition for 'TotalCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(16,20): error CS0117: 'Model' does not contain a definition for 'PageNum'
/root/office/wwwroot/Data/Common/_Page.cshtml(18,1): error CS0103: The name 'WriteAttributeValue' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(18,51): error CS0117: 'Model' does not contain a definition for 'Url'
/root/office/wwwroot/Data/Common/_Page.cshtml(18,62): error CS0117: 'Model' does not contain a definition for 'PageNum'
/root/office/wwwroot/Data/Common/_Page.cshtml(24,20): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(24,38): error CS0117: 'Model' does not contain a definition for 'ShowNumCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(24,64): error CS0117: 'Model' does not contain a definition for 'PageNum'
/root/office/wwwroot/Data/Common/_Page.cshtml(24,80): error CS0117: 'Model' does not contain a definition for 'ShowNumCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(26,1): error CS0103: The name 'WriteAttributeValue' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(26,51): error CS0117: 'Model' does not contain a definition for 'Url'
/root/office/wwwroot/Data/Common/_Page.cshtml(29,34): error CS0117: 'Model' does not contain a definition for 'Start'
/root/office/wwwroot/Data/Common/_Page.cshtml(29,54): error CS0117: 'Model' does not contain a definition for 'End'
/root/office/wwwroot/Data/Common/_Page.cshtml(31,34): error CS0117: 'Model' does not contain a definition for 'PageNum'
/root/office/wwwroot/Data/Common/_Page.cshtml(33,35): error CS0103: The name 'Write' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(37,1): error CS0103: The name 'WriteAttributeValue' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(37,51): error CS0117: 'Model' does not contain a definition for 'Url'
/root/office/wwwroot/Data/Common/_Page.cshtml(37,56): error CS0103: The name 'Write' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(41,20): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(41,38): error CS0117: 'Model' does not contain a definition for 'ShowNumCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(43,39): error CS0117: 'Model' does not contain a definition for 'ShowNumCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(44,24): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(44,42): error CS0117: 'Model' does not contain a definition for 'PageNum'
/root/office/wwwroot/Data/Common/_Page.cshtml(46,1): error CS0103: The name 'WriteAttributeValue' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(46,51): error CS0117: 'Model' does not contain a definition for 'Url'
/root/office/wwwroot/Data/Common/_Page.cshtml(46,62): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(46,67): error CS0103: The name 'Write' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(46,79): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(49,20): error CS0117: 'Model' does not contain a definition for 'PageNum'
/root/office/wwwroot/Data/Common/_Page.cshtml(49,36): error CS0117: 'Model' does not contain a definition for 'PageCount'
/root/office/wwwroot/Data/Common/_Page.cshtml(51,1): error CS0103: The name 'WriteAttributeValue' does not exist in the current context
/root/office/wwwroot/Data/Common/_Page.cshtml(51,51): error CS0117: 'Model' does not contain a definition for 'Url'
/root/office/wwwroot/Data/Common/_Page.cshtml(51,61): error CS0117: 'Model' does not contain a definition for 'PageNum'
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at QibuCore.Infrastructure.PagerHelper.PageAsync(IHtmlHelper html, String PagerId, ViewModel model, Int32 ShowNumCount) in D:\New\QibuOffie\Qibu\QibuCore\Infrastructure\PageHelper.cs:line 161
   at AspNetCore.Areas_ShopManage_Views_Order_Index.ExecuteAsync() in D:\New\QibuOffie\Qibu\Qibu\Areas\ShopManage\Views\Order\Index.cshtml:line 514
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
----------------------------------------------------------------

```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.
/cc @pranavkm

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/7969. https://github.com/aspnet/Mvc/issues/7969#issuecomment-400703711 has some workarounds for 2.1.1 \ 2.1.2 releases. The issue should be addresses as part of [2.1.3](https://github.com/aspnet/Mvc/pull/7989).
