### ISSUE TITLE
Test failure: VersionedApi_CanUseOrderToDisambiguate_OverlappingVersionRanges

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Mvc#8319]
This test [fails](http://aspnetci/viewLog.html?buildId=537374&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Microsoft.AspNetCore.Routing.RouteCreationException : An error occurred while creating the route with name 'default' and pattern '{controller=Home}/{action=Index}/{id?}'.
---- System.InvalidOperationException : The route parameter 'controller' has both an inline default value and an explicit default value specified. A route parameter cannot contain an inline default value when a default value is specified explicitly. Consider removing one of them.
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory) in /_/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcEndpointInfo.cs:line 39
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes) in /_/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs:line 109
   at VersioningWebSite.StartupWithEndpointRouting.Configure(IApplicationBuilder app) in /Users/asplab/TeamCity/work/33bdfc1cae7b2a38/modules/Mvc/test/WebSites/VersioningWebSite/StartupWithEndpointRouting.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.Mvc.FunctionalTests.MvcTestFixture`1.CreateServer(IWebHostBuilder builder) in /_/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Infrastructure/MvcTestFixture.cs:line 43
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer() in /_/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs:line 126
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers) in /_/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs:line 335
   at Microsoft.AspNetCore.Mvc.FunctionalTests.VersioningTestsBase`1..ctor(MvcTestFixture`1 fixture) in /_/test/Microsoft.AspNetCore.Mvc.FunctionalTests/VersioningTestsBase.cs:line 19
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitPart|10_3(RoutePatternPart part, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitSegment|10_2(RoutePatternPathSegment segment, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.PatternCore(String rawText, IDictionary`2 defaults, IDictionary`2 parameterPolicies, IEnumerable`1 segments)
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory) in /_/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcEndpointInfo.cs:line 24
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
VersionedApi_CanReachOtherVersionOperationsWithParameters_OnTheSameController [failed with about the same error](http://aspnetci/viewLog.html?buildId=537374&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pranavkm** [comment]
@JamesNK \ @rynowak could you have a look?

**Comment by rynowak** [comment]
This was not flakiness, it was a regression that was fixed a few weeks ago 👍
