### ISSUE TITLE
FireOnCompletedAwaited result in System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by muratg** [aspnet/Mvc#8325]
_From @werynguyen on August 10, 2018 1:1_

After migrating our high traffic aspnetcore app to Core 2.1.2, we start receiving this error

``` c#
System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesFeature.Dispose()
   at Microsoft.AspNetCore.Http.HttpResponse.<>c.<.cctor>b__30_1(Object disposable)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FireOnCompletedAwaited(Stack`1 onCompleted)
```
This happen about once every 5000 requests and very intermittently. We thought that this could be a concurrency locking issue as it always happens in pair but recently one of our apps report this error not in pair. 

Can anyone suggest any clue on why this is happening?

_Copied from original issue: aspnet/KestrelHttpServer#2802_

**Comment by muratg** [comment]
_From @Tratcher on August 10, 2018 1:4_

@rynowak ?

**Comment by muratg** [comment]
cc @mkArtakMSFT 

Based on the stack trace, this looks like MVC. If you guys agree, please move it over. Thanks.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/8260.
