### ISSUE TITLE
InvalidOperationException thrown in tag helpers using cache in 2.2.0 preview 1

### ISSUE THREAD

**Issue by martincostello** [aspnet/Mvc#8330]
#### Is this a Bug or Feature request?:

Bug (or breaking behaviour change)

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

See martincostello/website#228, run `Build.ps1` or `build.sh`.

#### Description of the problem:

I have some custom tag helpers in my code which derive from some built-in tag helper classes. Due to obsolete warnings on the constructor, as part of trying out 2.2.0 preview 1, I changed the constructor used to the new non-obsolete one ([commit](https://github.com/martincostello/website/commit/f32d0b1b4a49a70a240a73d216eede079b70725e)).

Now when the tests are run, various 500 errors occur due to the below exception.

```
 [2018-08-26 10:52:31Z] fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
       An unhandled exception has occurred while executing the request.
 System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.
    at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
    at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
    at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value, TimeSpan absoluteExpirationRelativeToNow)
    at MartinCostello.Website.TagHelpers.InlineStyleTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in C:\Coding\website\src\Website\TagHelpers\InlineStyleTagHelper.cs:line 118
```

It appears that due to [`TagHelperMemoryCacheProvider`](https://github.com/aspnet/Mvc/blob/a7301120b1971d6d047c63db5e6911aa134f99a2/src/Microsoft.AspNetCore.Mvc.Razor/Infrastructure/TagHelperMemoryCacheProvider.cs) using a fixed size, it is no longer possible to use the `Cache.Set(string, object)` method.

This appears to be a breaking behavioural change due to the internal implementation detail of using a private cache for tag helpers, rather than the overall cache.

Curiously, from my CI builds, this only appears to affect Windows and OS X, and not Linux.

  * [AppVeyor CI](https://ci.appveyor.com/project/martincostello/website/build/2.1.466/tests)
  * [Travis CI](https://travis-ci.org/martincostello/website/builds/420726554)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

`2.2.0-preview1-35029`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @martincostello.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
> It appears that due to TagHelperMemoryCacheProvider using a fixed size, it is no longer possible to use the Cache.Set(string, object) method. 

This is intentional. The recommendation is to use a custom instance of `IMemoryCache` if you need to continue using the `MemoryCache.Set`. Alternatively specifying the size is also viable. Yet another alternative is to continue using the [deprecated ctor for `ImageTagHelper`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.TagHelpers/ImageTagHelper.cs#L42-L51) - this should leave you unbroken until the 3.0
