### ISSUE TITLE
CI failure - HttpResponseMessageOutputFormatterTests (intermittent)

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#8371]
```
Microsoft.AspNetCore.Mvc.WebApiCompatShimTest.HttpResponseMessageOutputFormatterTests.Disposed_CalledOn_HttpResponseMessage [FAIL]
17:19:48   Failed   Microsoft.AspNetCore.Mvc.WebApiCompatShimTest.HttpResponseMessageOutputFormatterTests.Disposed_CalledOn_HttpResponseMessage
17:19:48   Error Message:
17:19:48    System.NullReferenceException : Object reference not set to an instance of an object.
17:19:48   Stack Trace:
17:19:48      at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
17:19:48      at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
17:19:48      at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
17:19:48      at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
17:19:48      at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
17:19:48      at Moq.Mock`1.<InitializeInstance>b__20_0()
17:19:48      at Moq.Mock`1.OnGetObject()
17:19:48      at Moq.Mock`1.get_Object()
17:19:48      at Microsoft.AspNetCore.Mvc.WebApiCompatShimTest.HttpResponseMessageOutputFormatterTests.Disposed_CalledOn_HttpResponseMessage() in /_/test/Microsoft.AspNetCore.Mvc.WebApiCompatShimTest/HttpResponseMessageOutputFormatterTests.cs:line 29
17:19:48   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by benaadams** [comment]
Saw in ea3f64a commit of https://github.com/aspnet/Mvc/pull/8368

**Comment by rynowak** [comment]
oh noes

**Comment by benaadams** [comment]
Concurrent use of Dictionary?

**Comment by benaadams** [comment]
Concurrent use of Dictionary? Is only way `Dictionary2.FindEntry(TKey key)` with throw https://github.com/dotnet/corefx/issues/31186

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/8157

**Comment by benaadams** [comment]
Yeah
