### ISSUE TITLE
Error when posting empty multipart/form-data content

### ISSUE THREAD

**Issue by chrischu** [aspnet/Mvc#8414]
I think I might've found a bug.

When using a controller like this:
```
[Route("api/[controller]")]
[ApiController]
public class ReproController : ControllerBase
{
  [HttpPost("post")]
  public void Post([FromForm] ReproModel model)
  {
  }
}

public class ReproModel
{
  [Required]
  public string Value{get; set; }
}
```

And POSTing a request like this:
```
POST http://localhost:62059/api/Repro/Post HTTP/1.1
Host: localhost:62059
Accept: */*
Connection: Keep-Alive
Content-Type: multipart/form-data; boundary=f7351699-0d96-4604-b20f-1d42f078b255
Content-Length: 0
```

I get an InternalServerError response, the exception is:
```
System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component. 
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
``` 

Interestingly enough when I remove the `Content-Type` header it works correctly (meaning it returns 400 BadRequest since the required model field is not given).

I'm using ASP.NET Core 2.1.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrischu.
@dougbu, can you please investigate this? Thanks!

**Comment by mkArtakMSFT** [comment]
@chrischu, it would be great if you could share with us a minimalistic repro project.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5631

**Comment by pranavkm** [comment]
We can continue using #5631 to figure out what to do next.
